'use strict';const test=require('node:test'),assert=require('node:assert/strict'),P=require('../src/investment_system/product/web_assets/device-profiles.js'),D=require('../src/investment_system/product/web_assets/profile-defaults.js');
test('official copy is isolated and respects canonical leaf axes without parent weights',()=>{const w=P.copyOfficial();w.Q[Object.keys(w.Q)[0]]=99;assert.notDeepEqual(w,D.weights);for(const axis of Object.values(P.copyOfficial()))assert.ok(Math.abs(Object.values(axis).reduce((a,b)=>a+b)-100)<1e-9);assert.deepEqual(Object.keys(D.weights).sort(),['G','Q','V']);});
test('invalid sums, NaN, prices, empty type config and extra fields fail closed',()=>{const p={schema:P.SCHEMA,strategies:[{id:'device-1',name:'Synthetic',weights:P.copyOfficial()}],types:[]};P.validate(p);for(const mutate of [x=>x.price=123,x=>x.strategies[0].weights.Q[Object.keys(x.strategies[0].weights.Q)[0]]=NaN,x=>x.strategies[0].weights.Q[Object.keys(x.strategies[0].weights.Q)[0]]+=1,x=>x.types.push({threshold:10})]){const x=structuredClone(p);mutate(x);assert.throws(()=>P.validate(x));}});
test('corrupt storage is preserved and roundtrip holds only configuration',()=>{const values=new Map([[P.KEY,'{bad json']]),storage={getItem:k=>values.get(k)||null,setItem:(k,v)=>values.set(k,v)};assert.throws(()=>P.read(storage));assert.equal(values.get(P.KEY),'{bad json');const p={schema:P.SCHEMA,strategies:[{id:'device-1',name:'Synthetic',weights:P.copyOfficial()}],types:[]};assert.deepEqual(P.write(storage,p),P.read(storage));});
test("previewRanks recalculates published Q/G factors in RAM and ranks official vs draft",()=>{const api=P,engine=require('../src/investment_system/product/web_assets/engine-preview.js'),factors=s=>Object.fromEntries([...Object.keys(api.copyOfficial().Q).map((f,i)=>[f,{score:s[i]??null,state:s[i]===undefined?'NOT_AVAILABLE':'LIVE'}]),...Object.keys(api.copyOfficial().G).map(f=>[f,{score:50,state:'LIVE'}])]),payload={data:{companies:{
 aaa:{state:'LIVE',factors:{...factors([90,10,10,10,10,10,10])}},bbb:{state:'LIVE',factors:{...factors([10,90,10,10,10,10,10])}},ccc:{state:'NOT_AVAILABLE',factors:{}}}}};const before=JSON.stringify(payload),draft=api.copyOfficial();draft.Q.competitive_advantage=5;draft.Q.roic_wacc=35;
 const r=api.previewRanks(payload,draft,engine);assert.equal(JSON.stringify(payload),before);assert.equal(r.state,'PREVIEW');assert.deepEqual(r.rows.map(x=>x.company_id),['bbb','aaa']);const a=r.rows.find(x=>x.company_id==='aaa'),b=r.rows.find(x=>x.company_id==='bbb');assert.equal(a.official,b.official);assert.ok(b.mine>a.mine);
 assert.equal(a.official_rank,1);assert.equal(a.mine_rank,2);assert.equal(a.rank_change,-1);assert.equal(b.rank_change,1);assert.deepEqual(api.previewRanks(null,draft,engine),{state:'NOT_AVAILABLE',reason:'PUBLIC_QG_NOT_AVAILABLE',rows:[]});
 assert.equal(api.previewRanks({data:{companies:{ccc:{state:'NOT_AVAILABLE',factors:{}}}}},draft,engine).state,'NOT_AVAILABLE');
 const qOnly=api.previewRanks({data:{companies:{ddd:{state:'LIVE',factors:{competitive_advantage:{score:0,state:'LIVE'}}}}}},draft,engine).rows[0];assert.equal(qOnly.official,null);assert.equal(qOnly.official_rank,null);assert.equal(qOnly.mine_q,0);assert.equal(qOnly.mine_g,null);});
