'use strict';const test=require('node:test'),assert=require('node:assert/strict'),fs=require('node:fs'),api=require('../src/investment_system/product/web_assets/engine-preview.js'),vectors=JSON.parse(fs.readFileSync(require('node:path').join(__dirname,'../tests/fixtures/python_js_reference_v1.json'),'utf8'));
function equal(a,b){if(typeof b==='number'){assert.equal(typeof a,'number');assert.ok(Number.isFinite(a)&&Math.abs(a-b)<=Math.max(1e-10,Math.abs(b)*1e-10));}else if(Array.isArray(b)){assert.ok(Array.isArray(a));assert.equal(a.length,b.length);b.forEach((v,i)=>equal(a[i],v));}else if(b&&typeof b==='object'){assert.deepEqual(Object.keys(a).sort(),Object.keys(b).sort());Object.keys(b).forEach(k=>equal(a[k],b[k]));}else assert.equal(a,b);}
for(const c of vectors.cases.filter(c=>['dcf','reverse_dcf','v_factors','strategy'].includes(c.operation)))test('canonical vector '+c.id,()=>{const fn={dcf:api.dcf,reverse_dcf:api.reverseDcf,v_factors:api.vFactors,strategy:api.strategy}[c.operation];const input=structuredClone(c.input),before=JSON.stringify(input);equal(fn(input),c.expected);assert.equal(JSON.stringify(input),before);});
for(const c of vectors.cases.filter(c=>c.operation==='company_types'))test('canonical type vector '+c.id,()=>{const input=structuredClone(c.input),before=JSON.stringify(input),config=api.compileCustomTypeConfig(input.config);assert.equal(config.state,'COMPILED');equal(api.companyTypes({metrics:input.metrics,original_qgv:input.original_qgv,config}),c.expected);assert.equal(JSON.stringify(input),before);});
test('type config: official label never promotes, invalid configs and raw objects fail closed',()=>{const cfg=structuredClone(vectors.cases.find(c=>c.operation==='company_types').input.config);cfg.status='OFFICIAL_PROVISIONAL';const h=api.compileCustomTypeConfig(cfg),r=api.companyTypes({metrics:{},original_qgv:{Q:1,G:2,V:3},config:h});assert.equal(r.role,'PREVIEW');assert.equal(r.config_status,'CUSTOM_PREVIEW');
assert.deepEqual(api.companyTypes({metrics:{},original_qgv:{},config:cfg}),{state:'INVALID_INPUT',reason_codes:['INVALID_INPUT']});const bad=structuredClone(cfg);bad.types[0].weights={Q:50,G:40,V:5};bad.types.push({...bad.types[0]});assert.deepEqual(api.compileCustomTypeConfig(bad).reason_codes,['WEIGHT_SUM','TYPE_ID_DUPLICATE']);const nan=structuredClone(cfg);nan.extra=NaN;assert.deepEqual(api.compileCustomTypeConfig(nan).reason_codes,['CONFIG_INVALID']);
assert.deepEqual(api.companyTypes({metrics:{},original_qgv:{Q:101},config:h}),{state:'INVALID_INPUT',reason_codes:['QGV_INVALID']});const missing=api.companyTypes({metrics:{},original_qgv:{Q:60,G:null,V:80},config:h});assert.equal(missing.adjusted_score,null);assert.deepEqual(missing.missing_pillars,['G']);});
test('type mixing: cyclical/defensive keep higher, one clamp then renormalize, normalized-earnings V required',()=>{const cfg=structuredClone(vectors.cases.find(c=>c.operation==='company_types').input.config);for(const t of cfg.types)if(t.id==='cyclical'||t.id==='defensive')t.rule={kind:'ramp',metric:t.id+'_m',lower:0,upper:1};const h=api.compileCustomTypeConfig(cfg);let r=api.companyTypes({metrics:{cyclical_m:.9,defensive_m:.8},original_qgv:{Q:60,G:70,V:80},config:h});assert.deepEqual(r.selected_types,['cyclical']);assert.equal(r.adjusted_qgv.V,null);assert.deepEqual(r.reason_codes,['NORMALIZED_EARNINGS_VALUE_REQUIRED']);
r=api.companyTypes({metrics:{cyclical_m:.9,cyclical_v_score:0},original_qgv:{Q:60,G:70,V:80},config:h});assert.equal(r.adjusted_qgv.V,0);assert.equal(r.original_qgv.V,80);assert.ok(Math.abs(r.weights.Q+r.weights.G+r.weights.V-100)<1e-9);});
test('Python binary64 nearest-even rounding, blocked observations and zero stay distinct',()=>{assert.equal(api.roundEven(2.675,2),2.67);assert.equal(api.roundEven(2.685,2),2.69);const zero=api.strategy({observations:{competitive_advantage:{score:0,quality:'OK'}}});assert.equal(zero.axes.Q.score,0);assert.equal(zero.axes.Q.coverage,'PARTIAL');assert.equal(api.strategy({observations:{competitive_advantage:{score:0,quality:'BLOCKED_DEPENDENCY'}}}).axes.Q.score,null);});
