'use strict';const {chromium}=require('playwright');
(async()=>{const browser=await chromium.launch({headless:true,executablePath:process.env.CHROMIUM_EXECUTABLE_PATH});let pass=0,fail=0;
try{for(const width of [390,1440]){const context=await browser.newContext({viewport:{width,height:900},serviceWorkers:'block'}),page=await context.newPage();
 await page.route('**/*',r=>new URL(r.request().url()).origin===new URL(process.env.PAGES_COCKPIT_URL).origin?r.continue():r.abort());
 await page.addInitScript(()=>{window.__popupMode='popup_failed_to_open';window.google={accounts:{oauth2:{initTokenClient(config){return{requestAccessToken(){if(window.__popupMode)config.error_callback({type:window.__popupMode,message:'provider private text'});else config.callback({access_token:['synthetic','ram'].join('-'),expires_in:3600,scope:'email openid https://www.googleapis.com/auth/userinfo.email https://www.googleapis.com/auth/drive.file profile'});}};},revoke(_,done){done({});}}}};});
 await page.goto(process.env.PAGES_COCKPIT_URL+'#settings');const root=page.locator('[data-google-sheet-quotes]');await root.locator('[data-sheet-enabled]').check();await root.locator('[data-sheet-action="login"]:enabled').waitFor();
 for(const [mode,code] of [['popup_failed_to_open','AUTH_POPUP_FAILED_TO_OPEN'],['popup_closed','AUTH_POPUP_CLOSED'],['private unsupported','AUTH_POPUP_UNKNOWN']]){await page.evaluate(x=>window.__popupMode=x,mode);await root.locator('[data-sheet-action="login"]').click();await root.locator('[data-sheet-notice]').filter({hasText:code}).waitFor();if((await root.textContent()).includes('provider private text'))throw Error('PRIVATE_TEXT');}
 await page.evaluate(()=>window.__popupMode='');await root.locator('[data-sheet-action="login"]').click();await root.locator('[data-sheet-action="disconnect"]').waitFor();
 if(await page.evaluate(()=>JSON.stringify({...localStorage}).includes(['synthetic','ram'].join('-'))))throw Error('TOKEN_STORED');await root.locator('[data-sheet-action="disconnect"]').click();await root.locator('[data-sheet-action="login"]').waitFor();pass++;console.log('PASS expanded scope and popup UI '+width);await context.close();}
}catch(_){fail++;console.log('FAIL login browser');}finally{await browser.close();}console.log('COUNTS pass='+pass+' fail='+fail);if(fail)process.exitCode=1;})();
