/* Actual setup and shared OAuth session; all Google transport uses synthetic contracts. */
'use strict';const {chromium}=require('playwright');const assert=require('node:assert/strict');
const BASE=process.env.PAGES_COCKPIT_URL,NEW='n'.repeat(30),EXISTING='e'.repeat(30),TOKEN=['synthetic','picker','ram'].join('-');
(async()=>{const browser=await chromium.launch({headless:true,executablePath:process.env.CHROMIUM_EXECUTABLE_PATH});let pass=0,fail=0,phase='INIT';
try{for(const width of [390,1440]){const context=await browser.newContext({viewport:{width,height:900},serviceWorkers:'block'}),page=await context.newPage();page.setDefaultTimeout(10000);let creates=0,headers=0,unsafe=0,pageErrors=0,posted,broken=false,permission=false;
page.on('pageerror',()=>pageErrors++);
await page.addInitScript(()=>{window.__setupCsp=0;document.addEventListener('securitypolicyviolation',()=>window.__setupCsp++);window.__setupScopes=[];window.__pickerShow=0;
 const picker={ViewId:{SPREADSHEETS:'spreadsheets'},Response:{ACTION:'action',DOCUMENTS:'docs'},Action:{PICKED:'picked',CANCEL:'cancel'},Document:{MIME_TYPE:'mimeType',ID:'id'},DocsView:class{setMimeTypes(value){if(value!=='application/vnd.google-apps.spreadsheet')throw Error('INVALID');}},PickerBuilder:class{
 addView(){return this;}setOAuthToken(value){if(value!==['synthetic','picker','ram'].join('-'))throw Error('INVALID');return this;}setDeveloperKey(){return this;}setAppId(){return this;}setOrigin(value){if(value!==location.origin)throw Error('INVALID');return this;}setCallback(fn){window.__pickerCallback=fn;return this;}build(){return{setVisible(value){if(value)window.__pickerShow++;},dispose(){}};}}};
 window.google={picker,accounts:{oauth2:{initTokenClient(config){window.__setupScopes.push(config.scope);return{requestAccessToken(){if(!navigator.userActivation.isActive)throw Error('GESTURE');config.callback({access_token:['synthetic','picker','ram'].join('-'),expires_in:3600,scope:'https://www.googleapis.com/auth/drive.file email openid profile https://www.googleapis.com/auth/userinfo.email'});}};},revoke(_,done){done({});}}}};});
await page.route('**/*',async r=>{const request=r.request(),u=new URL(request.url());if(u.origin===new URL(BASE).origin){if(u.pathname.endsWith('/universe-codes.json'))return r.fulfill({status:404,body:''});return r.continue();}
 if(u.origin==='https://sheets.googleapis.com'){const cors={'access-control-allow-origin':new URL(BASE).origin,'access-control-allow-headers':'Authorization, Content-Type','access-control-allow-methods':'GET, POST'};
 if(request.method()==='OPTIONS')return r.fulfill({status:204,headers:cors});if(request.headers().authorization!=='Bearer '+TOKEN||request.headers().referer||request.headers().cookie)unsafe++;
 if(request.method()==='POST'){creates++;posted=JSON.parse(request.postData());return r.fulfill({headers:cors,contentType:'application/json',body:JSON.stringify({spreadsheetId:NEW})});}
 if(request.method()!=='GET'){unsafe++;return r.abort();}if(permission)return r.fulfill({status:403,headers:cors,contentType:'application/json',body:'{"error":{"message":"private provider diagnostic"}}'});
 if(u.pathname.includes('/values/')){headers++;const range=decodeURIComponent(u.pathname.split('/values/')[1]);let values;if(range==="'Quotes'!A1:C1")values=[['code','price','tradetime']];else if(range==="'Trades'!A1:D1")values=[['date','symbol','B/S','quantity']];else if(range==="'Universe'!A1:C1")values=[[broken?'private wrong cell':'code','marketcap','price']];else{unsafe++;return r.abort();}return r.fulfill({headers:cors,contentType:'application/json',body:JSON.stringify({values})});}
 return r.fulfill({headers:cors,contentType:'application/json',body:JSON.stringify({sheets:['Quotes','Trades','Universe'].map(title=>({properties:{title}}))})});
 }unsafe++;return r.abort();});
phase='SIGN_IN';await page.goto(BASE+'#settings');const root=page.locator('[data-google-first-setup]');await page.locator('[data-sheet-enabled]').waitFor();await root.locator('[data-setup-action="login"]').click();
if(await root.locator('[data-setup-action="login"]').isVisible())await root.locator('[data-setup-action="login"]').click();
phase='AUTO_CREATE';await root.locator('[data-setup-checks]').filter({hasText:'Universe · 탭 ✓ · 머리글 ✓'}).waitFor();phase='CREATE_COUNT';assert.equal(creates,1);phase='CREATE_TEMPLATE';assert.equal(posted.sheets[2].data[0].rowData.length,1);assert.equal(posted.sheets[0].data[0].rowData.length,20);phase='PREPARING_LABEL';assert.equal(await root.locator('[data-universe-preparing]').textContent(),'종목 목록 준비 중');assert.ok(await root.locator('[data-universe-preparing]').isVisible());
phase='EXACT_SCOPE';assert.ok(await page.evaluate(()=>window.__setupScopes.every(s=>s==='https://www.googleapis.com/auth/drive.file email')));phase='ADVANCED';assert.equal(await page.locator('[data-sheet-advanced]').getAttribute('open'),null);
phase='PICK_EXISTING_504';await root.locator('[data-setup-action="picker"]').click();await page.waitForFunction(()=>window.__pickerShow===1);await page.evaluate(id=>window.__pickerCallback({action:'picked',docs:[{id,mimeType:'application/vnd.google-apps.spreadsheet'}]}),EXISTING);await page.waitForFunction(id=>GoogleSheetSetup.source(window)===id,EXISTING);await root.locator('[data-setup-action="check"]:enabled').waitFor();assert.equal(creates,1);assert.equal(await page.evaluate(()=>PrivateTrades.source(window)),EXISTING);
// The pre-existing Universe can contain 504 data rows: setup reads only its header, never rewrites it.
phase='HEADERS';broken=true;await root.locator('[data-setup-action="check"]').click();await root.locator('[data-setup-checks]').filter({hasText:'Universe · 탭 ✓ · 머리글 ✗'}).waitFor();assert.ok(!(await root.textContent()).includes('private wrong cell'));broken=false;await root.locator('[data-setup-action="check"]').click();await root.locator('[data-setup-checks]').filter({hasText:'Universe · 탭 ✓ · 머리글 ✓'}).waitFor();
phase='PERMISSION';permission=true;await root.locator('[data-setup-action="check"]').click();await root.locator('[data-setup-status]').filter({hasText:'DRIVE_FILE_PERMISSION_REQUIRED'}).waitFor();assert.ok(!(await root.textContent()).includes('private provider diagnostic'));permission=false;
phase='PRIVACY';const safe=await page.evaluate(async({ids,token})=>{const c=await(await fetch('actual-catalog.json')).json(),backup=JSON.stringify(await DeviceBackup.read(window,c));if([...ids,token].some(x=>backup.includes(x)))return false;if(JSON.stringify({...localStorage}).includes(token)||JSON.stringify({...sessionStorage}).includes(token))return false;const settings=await DeviceActual.sheetSettings(window);return settings.spreadsheet_id===ids[1]&&settings.range==="'Quotes'!A1:C1025"&&!JSON.stringify(GoogleSheetQuotes.sessionFor(window,InvestmentAppConfig.googleSheetsClientId)).includes(token);},{ids:[NEW,EXISTING],token:TOKEN});assert.ok(safe);
phase='PICKER_LOGOUT';await root.locator('[data-setup-action="picker"]').click();await page.waitForFunction(()=>window.__pickerShow===2);await page.evaluate(()=>GoogleSheetQuotes.sessionFor(window,InvestmentAppConfig.googleSheetsClientId).disconnect());await page.evaluate(id=>window.__pickerCallback({action:'picked',docs:[{id,mimeType:'application/vnd.google-apps.spreadsheet'}]}),NEW);assert.equal(await page.evaluate(()=>GoogleSheetSetup.source(window)),EXISTING);
assert.equal(unsafe,0);assert.equal(pageErrors,0);assert.equal(await page.evaluate(()=>window.__setupCsp),0);assert.ok(headers>=12);assert.ok(await page.evaluate(()=>document.documentElement.scrollWidth<=innerWidth));pass++;console.log('PASS automatic header-only setup and read-only existing Picker '+width);await context.close();}
}catch(_){fail++;console.log('FAIL sheet setup browser '+phase);}finally{await browser.close();}console.log('COUNTS pass='+pass+' fail='+fail);if(fail)process.exitCode=1;})();
