'use strict';const assert=require('node:assert/strict'),fs=require('node:fs'),path=require('node:path');const filename=path.join(__dirname,'../src/investment_system/product/web_assets/private-subset.js'),api=fs.existsSync(filename)?require(filename):{};
const AT='2030-02-10T12:00:00Z';let pass=0,fail=0;async function test(name,f){try{await f();pass++;console.log('PASS '+name);}catch(_){fail++;console.log('FAIL '+name);}}
async function fixture(i=1){const seed={listing_id:'listing_'+i,company_id:'synthetic_'+i,issuer_id:'issuer_'+i,security_id:'security_'+i,symbol:'S'+i,mic:'XNYS',currency:'USD',timezone:'America/New_York',provider_symbol:'S'+i,cik:String(i).padStart(10,'0'),valid_from:'2020-01-01',valid_to:null,identity_evidence_ref:'synthetic',identity_sha256:await api.digest('synthetic'),synthetic:true};
 const basis={listing_id:seed.listing_id,company_id:seed.company_id,security_id:seed.security_id,basis_status:'SINGLE_CLASS_CONFIRMED',source_evidence_ref:'synthetic',source_sha256:await api.digest('unit'),available_at:'2030-02-09T12:00:00Z',share_unit:'shares',price_basis:'GOOGLEFINANCE_CURRENT',currency:'USD',synthetic:true,share_class_basis:'ALIGNED'};
 const accn=String(i).padStart(10,'0')+'-30-000001',row={end:'2030-01-31',val:10,accn,form:'10-K',filed:'2030-02-01'},facts=JSON.stringify({cik:i,facts:{dei:{EntityCommonStockSharesOutstanding:{units:{shares:[row]}}},'us-gaap':{CommonStockSharesOutstanding:{units:{shares:[{...row,val:99}]}}}}}),sub=JSON.stringify({cik:i,filings:{recent:{accessionNumber:[accn],form:['10-K'],filingDate:['2030-02-01'],acceptanceDateTime:['2030-02-01T12:00:00Z']}}});
 const sec={cik:seed.cik,companyfacts_body:facts,submissions_body:sub,acquired_at:AT,facts_sha256:await api.digest(facts),submissions_sha256:await api.digest(sub),synthetic:true};return{seed,basis,sec};}
async function parsed(values,lookup){return api.parseUniverseValues(values,{source:'GOOGLEFINANCE_PRIVATE_UNIVERSE',acquired_at:AT,content_sha256:await api.digest(api.canonicalValues(values)),job_id:'synthetic_job',session_epoch:1,synthetic:true},lookup);}
async function checked(google=90,price=10,basisChanges={}){const f=await fixture(),p=await parsed([['code','marketcap','price'],['NYSE:S1',google,price]],{'NYSE:S1':f.seed}),basis={...f.basis,...basisChanges},sh=await api.prepareSecShares(f.seed,f.sec,basis,AT),pr=api.prepareUniversePrice(p.rows[0],basis,AT);return{f,p,sh,pr,c:api.compareUniverseMarketCap(p.rows[0],sh,pr)};}
(async()=>{
 await test('SEC dei preference and inclusive ten percent R denominator',async()=>{const {c,sh}=await checked();assert.equal(sh.shares,10);assert.equal(c.recomputed_cap,100);assert.equal(c.quality,'MISMATCH');assert.equal(c.relative_difference,.1);assert.equal(c.state,'VERIFIED');assert.equal((await checked(91)).c.quality,'WITHIN_TOLERANCE');});
 await test('missing Google cap uses verified R without filling Sheet input',async()=>{const {c,p}=await checked(null);assert.equal(c.recomputed_cap,100);assert.equal(c.quality,'GOOGLE_MCAP_MISSING');assert.equal(p.rows[0].google_mcap,null);assert.equal((await checked(100,null)).c.state,'NOT_AVAILABLE');});
 await test('share class difference requires explicit evidence and has no corrected cap',async()=>{const {c,sh}=await checked(90,10,{share_class_basis:'DIFFERENT'});assert.equal(sh.reason_codes[0],'SHARE_CLASS_BASIS');assert.equal(c.quality,'SHARE_CLASS_BASIS');assert.equal(c.recomputed_cap,null);assert.equal(c.state,'NOT_AVAILABLE');assert.equal((await checked(1)).c.quality,'MISMATCH');});
 await test('hash accession basis identity future and mixed inputs fail closed',async()=>{const f=await fixture();assert.equal((await api.prepareSecShares(f.seed,{...f.sec,facts_sha256:'0'.repeat(64)},f.basis,AT)).reason_codes[0],'MANIFEST_MISMATCH');assert.equal((await api.prepareSecShares(f.seed,f.sec,{...f.basis,basis_status:'UNKNOWN'},AT)).reason_codes[0],'BASIS_UNCONFIRMED');assert.equal((await api.prepareSecShares(f.seed,{...f.sec,acquired_at:'2030-02-11T12:00:00Z'},f.basis,AT)).reason_codes[0],'AVAILABLE_AFTER_AS_OF');assert.equal((await api.prepareSecShares(f.seed,{...f.sec,synthetic:false},f.basis,AT)).reason_codes[0],'MIXED_SYNTHETIC_INPUT');});
 await test('Universe fixed columns invalid decimals duplicate conflicts and row limit',async()=>{const f=await fixture(),lookup={'NYSE:S1':f.seed};const p=await parsed([['NYSE:S1',100,10],['NYSE:S1',100,11]],lookup);assert.equal(p.row_count,1);assert.equal(p.rows[0].reason_codes[0],'INVALID_INPUT');const bad=await parsed([['NYSE:S1','1e9',true]],lookup);assert.equal(bad.rows[0].google_mcap,null);assert.equal(bad.rows[0].sheet_price,null);assert.equal((await parsed(Array.from({length:1024},(_,i)=>['unknown'+i,100,10]),{})).row_limit_reached,true);});
 await test('default N20 ranks R and remains partial for missing rows',async()=>{const fixtures=await Promise.all(Array.from({length:25},(_,i)=>fixture(i+1))),values=fixtures.map((f,i)=>['NYSE:'+f.seed.symbol,1,10+i]),lookup=Object.fromEntries(fixtures.map(f=>['NYSE:'+f.seed.symbol,f.seed])),p=await parsed(values,lookup),checks=[];for(let i=0;i<25;i++){const f=fixtures[i],row=p.rows[i],sh=await api.prepareSecShares(f.seed,f.sec,f.basis,AT);checks.push(api.compareUniverseMarketCap(row,sh,api.prepareUniversePrice(row,f.basis,AT)));}const s=api.selectVerifiedUniverseTopN(checks,p);assert.equal(s.selected_count,20);assert.equal(s.status,'COMPLETE');assert.equal(s.selected[0].listing.company_id,'synthetic_25');assert.equal(s.selected[0].effective_cap,340);assert.equal(api.selectVerifiedUniverseTopN(checks.slice(1),p).status,'PARTIAL');const bad=[{...checks[0],content_sha256:'0'.repeat(64)},...checks.slice(1)];assert.equal(api.selectVerifiedUniverseTopN(bad,p).reason_codes[0],'MANIFEST_MISMATCH');});
 await test('asynchronous receipt parsing snapshots values and never mutates inputs',async()=>{const f=await fixture(),values=[['NYSE:S1',100,10]],before=JSON.stringify(values),r={source:'GOOGLEFINANCE_PRIVATE_UNIVERSE',acquired_at:AT,content_sha256:await api.digest(api.canonicalValues(values)),job_id:'synthetic_job',session_epoch:1,synthetic:true};const promise=api.parseUniverseValues(values,r,{'NYSE:S1':f.seed});values[0][2]=999;const p=await promise;assert.equal(p.rows[0].sheet_price,10);assert.ok(Object.isFrozen(p.rows[0].listing));assert.equal((await parsed(JSON.parse(before),{'NYSE:S1':f.seed})).row_count,1);});
 console.log('COUNTS pass='+pass+' fail='+fail);if(fail)process.exitCode=1;
})();
