'use strict';const {chromium}=require('playwright'),assert=require('node:assert/strict');
const BASE=process.env.PAGES_COCKPIT_URL;
(async()=>{const browser=await chromium.launch({headless:true,executablePath:process.env.CHROMIUM_EXECUTABLE_PATH});let phase='START',pass=0,fail=0;
try{for(const width of [390,1440]){const context=await browser.newContext({viewport:{width,height:900},serviceWorkers:'allow'}),page=await context.newPage();page.setDefaultTimeout(15000);let errors=0;page.on('pageerror',()=>errors++);await page.addInitScript(()=>{window.__pwaCsp=0;document.addEventListener('securitypolicyviolation',()=>window.__pwaCsp++);});
phase='READY';await page.goto(BASE+'#settings');await page.locator('[data-pwa-status]').waitFor();await page.evaluate(()=>navigator.serviceWorker.ready);await page.waitForFunction(()=>!!navigator.serviceWorker.controller);const registration=await page.evaluate(async()=>{const r=await navigator.serviceWorker.getRegistration();return{scope:r.scope,script:r.active.scriptURL};});assert.equal(registration.scope,new URL('.',BASE).href);assert.equal(registration.script,new URL('service-worker.js',BASE).href);
phase='CACHE_BOUNDARY';await page.evaluate(()=>{localStorage.setItem('synthetic-private-local','SYNTHETIC_PRIVATE_OFFLINE_CANARY');sessionStorage.setItem('synthetic-private-session','SYNTHETIC_PRIVATE_OFFLINE_CANARY');});await page.goto(BASE+'#company/nvda');await page.locator('[data-private-history]').waitFor();await page.evaluate(()=>fetch('sec-public-inputs.json',{cache:'no-store'}));const entries=await page.evaluate(async()=>{const out=[];for(const name of await caches.keys()){const cache=await caches.open(name);for(const request of await cache.keys()){const response=await cache.match(request);out.push({url:request.url,canary:(response.headers.get('content-type')||'').includes('image/')?false:(await response.text()).includes('SYNTHETIC_PRIVATE_OFFLINE_CANARY')});}}return out;});assert.equal(entries.length,5);assert.ok(entries.every(row=>/\/(offline\.html|style\.css|manifest\.json|icon-(192|512)\.png)$/.test(row.url)&&!row.canary));
phase='OFFLINE';await context.setOffline(true);await page.reload({waitUntil:'domcontentloaded'});await page.getByText('OFFLINE · STATIC SHELL',{exact:true}).waitFor();assert.ok((await page.locator('main').textContent()).includes('NOT_AVAILABLE'));assert.ok(!(await page.locator('body').textContent()).includes('SYNTHETIC_PRIVATE_OFFLINE_CANARY'));assert.equal(await page.locator('script').count(),0);assert.equal(await page.locator('#primary-nav a').count(),5);assert.ok(await page.evaluate(()=>document.documentElement.scrollWidth<=innerWidth));assert.equal(errors,0);
phase='ONLINE';await context.setOffline(false);await page.getByRole('link',{name:'다시 연결 / Reconnect',exact:true}).click();await page.locator('.hero').waitFor();await page.goto(BASE+'?reconnect=1#settings');await page.locator('[data-pwa-status]').waitFor();assert.equal(await page.evaluate(()=>localStorage.getItem('synthetic-private-local')),'SYNTHETIC_PRIVATE_OFFLINE_CANARY');assert.equal(await page.evaluate(()=>window.__pwaCsp),0);pass++;console.log('PASS install scope and private-free offline shell '+width);await context.close();}
}catch(_){fail++;console.log('FAIL PWA '+phase);}finally{await browser.close();}console.log('COUNTS pass='+pass+' fail='+fail);if(fail)process.exitCode=1;})();
