'use strict';
const assert=require('node:assert/strict'),fs=require('node:fs'),path=require('node:path'),vm=require('node:vm');
const source=path.join(__dirname,'../src/investment_system/product/web_assets/chart-indicators.js'),api=fs.existsSync(source)?require(source):{};
let pass=0,fail=0;function test(name,fn){try{fn();pass++;console.log('PASS '+name);}catch(_){fail++;console.log('FAIL '+name);}}
function bars(n,price=i=>100+i){return Array.from({length:n},(_,i)=>{const close=price(i);return {timestamp:1000000+i*86400,session_status:'COMPLETE',close,adjusted_close:close/2,open:close,high:close+2,low:close-2};});}
const by=(r,id)=>r.indicators.find(x=>x.indicator_id===id),close=(a,b)=>assert.ok(Math.abs(a-b)<=1e-10*Math.max(1,Math.abs(b)));
test('fixed periods role and SMA240 OFF',()=>{const r=api.calculate(bars(260));assert.equal(r.role,'RESEARCH_DISPLAY_ONLY');assert.equal(r.indicators.length,13);assert.equal(by(r,'SMA_240'),undefined);for(const item of r.indicators)assert.equal(item.role,r.role);assert.equal(by(r,'SMA_120').default_visible,true);assert.equal(by(api.calculate(bars(260),{includeSma240:true}),'SMA_240').default_visible,false);});
test('warmup exact boundaries and hand-computed linear inputs',()=>{
 const r=api.calculate(bars(260),{includeSma240:true});for(const n of [5,20,60,120,240]){const x=by(r,'SMA_'+n);assert.equal(x.values[n-2],null);close(x.values[n-1],100+(n-1)/2);}
 for(const [id,first] of [['EMA_20',19],['RSI_14',14],['MACD_12_26',25],['MACD_SIGNAL_9',33],['MACD_HISTOGRAM_12_26_9',33],['BOLL_UPPER_20_2',19],['ATR_14',14]]){const x=by(r,id);assert.equal(x.values[first-1],null);assert.notEqual(x.values[first],null);}
 close(by(r,'EMA_20').values[19],109.5);close(by(r,'EMA_20').values[20],110.5);close(by(r,'RSI_14').values[14],100);close(by(r,'ATR_14').values[14],4);close(by(r,'BOLL_UPPER_20_2').values[19],109.5+2*Math.sqrt(33.25));
});
test('Wilder recurrence and MACD linear components match hand calculation',()=>{const x=bars(40);x[15]={...x[15],open:111,close:111,adjusted_close:55.5,high:116,low:106};const r=api.calculate(x);close(by(r,'RSI_14').values[15],81.25);close(by(r,'ATR_14').values[15],4+6/14);const linear=api.calculate(bars(40));close(by(linear,'MACD_12_26').values[25],7);close(by(linear,'MACD_SIGNAL_9').values[33],7);close(by(linear,'MACD_HISTOGRAM_12_26_9').values[33],0);assert.ok(by(api.calculate(bars(119)),'SMA_120').values.every(x=>x===null));});
test('RSI decline zero and flat undefined stay distinct',()=>{assert.equal(by(api.calculate(bars(40,i=>200-i)),'RSI_14').values[14],0);const flat=by(api.calculate(bars(40,()=>100)),'RSI_14');assert.equal(flat.values[14],null);assert.equal(flat.unavailable_reasons[14],'ZERO_TOTAL_CHANGE');});
test('missing and incomplete sessions reset rather than bridge',()=>{const input=bars(70);input[30]={...input[30],open:null,high:null,low:null,close:null,adjusted_close:null};const r=api.calculate(input);for(const id of ['SMA_20','EMA_20','RSI_14','MACD_12_26','ATR_14'])assert.equal(by(r,id).values[30],null);assert.equal(by(r,'SMA_20').values[49],null);assert.notEqual(by(r,'SMA_20').values[50],null);const newer=bars(35);newer[34].session_status='IN_PROGRESS';assert.equal(by(api.calculate(newer),'EMA_20').values[34],null);});
test('adjusted closes never mix with raw ATR and no close fallback',()=>{const input=bars(40),r=api.calculate(input,{priceBasis:'PROVIDER_ADJUSTED_CLOSE'});close(by(r,'SMA_20').values[19],109.5/2);assert.ok(by(r,'ATR_14').values.every(x=>x===null));assert.equal(by(r,'ATR_14').unavailable_reasons[14],'OHLC_BASIS_UNCONFIRMED');input[20].adjusted_close=null;assert.equal(by(api.calculate(input,{priceBasis:'PROVIDER_ADJUSTED_CLOSE'}),'SMA_20').values[20],null);});
test('invalid ordering values and config fail closed',()=>{assert.equal(api.calculate(bars(20),{includeSma240:'true'}).state,'NOT_AVAILABLE');const x=bars(20);x[4].timestamp=x[3].timestamp;assert.equal(api.calculate(x).state,'NOT_AVAILABLE');x[4].timestamp+=86400;x[4].close=Infinity;assert.equal(api.calculate(x).state,'NOT_AVAILABLE');});
test('finite extreme prices and independent overflow handling',()=>{const x=bars(25,()=>Number.MAX_VALUE);x.forEach(b=>{b.open=b.high=b.low=b.close;});const r=api.calculate(x);assert.equal(by(r,'SMA_20').values[19],Number.MAX_VALUE);assert.ok(r.indicators.flatMap(x=>x.values).every(x=>x===null||Number.isFinite(x)));});
test('inputs remain unchanged results immutable no network or storage',()=>{const x=bars(40),before=JSON.stringify(x),r=api.calculate(x);assert.equal(JSON.stringify(x),before);assert.ok(Object.isFrozen(r)&&Object.isFrozen(r.indicators)&&Object.isFrozen(r.indicators[0].values));const context={fetch(){throw Error('IO');}};Object.defineProperty(context,'localStorage',{get(){throw Error('STORAGE');}});vm.runInNewContext(fs.readFileSync(source,'utf8'),context);assert.equal(context.ResearchIndicators.calculate(x).role,'RESEARCH_DISPLAY_ONLY');});
test('Codex2 synthetic reference components agree at seed and later sessions',()=>{
 const fixture=JSON.parse(fs.readFileSync(path.join(__dirname,'../tests/fixtures/technical_research_reference.json'),'utf8'));assert.equal(fixture.synthetic,true);
 const x=bars(260,i=>100+(i*7)%19+Math.floor(i/6));x.forEach((b,i)=>{b.high=b.close+2+i%3;b.low=b.close-2-i%2;});const r=api.calculate(x,{includeSma240:true});
 for(const [id,expected]of Object.entries(fixture.expected))for(const [index,value]of Object.entries(expected)){const actual=by(r,id).values[Number(index)];if(value===null)assert.equal(actual,null);else close(actual,value);}
});
console.log('COUNTS pass='+pass+' fail='+fail);if(fail)process.exitCode=1;
