'use strict';const {chromium}=require('playwright'),assert=require('node:assert/strict'),{fixture,unavailable}=require('./sec_reported_fixture.js');
const BASE=process.env.PAGES_COCKPIT_URL;
(async()=>{const browser=await chromium.launch({headless:true,executablePath:process.env.CHROMIUM_EXECUTABLE_PATH});let phase='START',pass=0,fail=0;
try{for(const width of [390,1440]){const context=await browser.newContext({viewport:{width,height:900},serviceWorkers:'block'}),page=await context.newPage();page.setDefaultTimeout(10000);let errors=0,variant=3;page.on('pageerror',()=>errors++);await page.addInitScript(()=>{window.__secCsp=0;document.addEventListener('securitypolicyviolation',()=>window.__secCsp++);});
await page.route('**/sec-public-inputs.json',r=>{if(variant===0)return r.fulfill({status:404,body:''});const p=fixture(variant);if(variant===3){p.companies[0].excluded_fact_counts={VALUE_INVALID:3,CLASS_SPLIT:2};p.companies[0].share_class_notice='SHARE_CLASS_BASIS';p.companies[1]=unavailable(p.companies[1],2);}return r.fulfill({contentType:'application/json',body:JSON.stringify(p)});});
phase='V3';await page.goto(BASE+'#leaderboard');const card=page.locator('[data-sec-reported]');await card.waitFor();assert.equal(await card.locator('[data-sec-company]').count(),17);assert.equal(await card.locator('[data-sec-company="amd"] [data-sec-excluded="VALUE_INVALID"]').textContent(),'VALUE_INVALID · 3');assert.equal(await card.locator('[data-sec-notice]').count(),2);assert.ok((await card.locator('[data-sec-company="amzn"]').textContent()).includes('NOT_AVAILABLE'));
phase='DETAIL';await page.goto(BASE+'#company/amd');await page.locator('[data-sec-company="amd"]').waitFor();assert.equal(await page.locator('[data-sec-company]').count(),1);assert.equal(await page.locator('[data-sec-excluded="CLASS_SPLIT"]').textContent(),'CLASS_SPLIT · 2');
phase='PRICE_BOUNDARY';assert.ok(!/reported_shares|0000000001-25-000001|https:\/\/data.sec.gov/.test(await page.locator('[data-sec-reported]').textContent()));assert.equal(await page.evaluate(()=>JSON.stringify({...localStorage,...sessionStorage}).includes('SEC_NO_ELIGIBLE_SHARE_FACTS')),false);
for(const v of [1,2,0]){variant=v;phase='LEGACY_'+v;await page.goto(BASE+'#leaderboard');await page.reload();await page.locator('[data-sec-reported]').waitFor();if(v)assert.ok((await page.locator('[data-sec-reported]').textContent()).includes('제외 개수: NOT_AVAILABLE (이전 입력)'));else await page.locator('[data-sec-unavailable]').waitFor();}
phase='LAYOUT';assert.equal(errors,0);assert.equal(await page.evaluate(()=>window.__secCsp),0);assert.ok(await page.evaluate(()=>document.documentElement.scrollWidth<=innerWidth));pass++;console.log('PASS SEC v3 notices, unavailable rows and legacy fallback '+width);await context.close();}
}catch(_){fail++;console.log('FAIL SEC consumer '+phase);}finally{await browser.close();}console.log('COUNTS pass='+pass+' fail='+fail);if(fail)process.exitCode=1;})();
