'use strict';const {chromium}=require('playwright'),assert=require('node:assert/strict');const BASE=process.env.PAGES_COCKPIT_URL;
(async()=>{const browser=await chromium.launch({headless:true,executablePath:process.env.CHROMIUM_EXECUTABLE_PATH});let phase='START',pass=0,fail=0;
try{for(const locale of ['ko-KR','en-US'])for(const width of [390,1440]){const context=await browser.newContext({viewport:{width,height:900},serviceWorkers:'block'}),page=await context.newPage();page.setDefaultTimeout(8000);let external=0,errors=0;page.on('pageerror',()=>errors++);await page.addInitScript(locale=>{localStorage.setItem('investment.web.v1.settings',JSON.stringify({version:1,display_locale:locale,source_language:'all'}));window.__importCsp=0;window.__importWrites=0;window.__importChanges=0;document.addEventListener('securitypolicyviolation',()=>window.__importCsp++);document.addEventListener('device-actual-changed',()=>window.__importChanges++);},locale);
await page.route('**/*',r=>{if(new URL(r.request().url()).origin===new URL(BASE).origin)return r.continue();external++;return r.abort();});
phase='FOLD';await page.goto(BASE+'#settings');const root=page.locator('[data-google-sheet-quotes]'),advanced=root.locator('[data-sheet-import-advanced]');await root.locator('[data-sheet-paste]').waitFor({state:'attached'});assert.equal(await advanced.count(),1);assert.equal(await advanced.getAttribute('open'),null);assert.equal(await root.locator('[data-sheet-paste]').isVisible(),false);assert.equal(await root.locator('[data-sheet-history]').isVisible(),false);await advanced.locator('summary').click();assert.ok(await root.locator('[data-sheet-paste]').isVisible());assert.ok(await root.locator('[data-sheet-history]').isVisible());
await page.evaluate(()=>{const original=DeviceActual.applyMarketImport;window.DeviceActual={...DeviceActual,applyMarketImport(...args){window.__importWrites++;return original(...args);}};});
const history=()=>page.evaluate(async()=>DeviceActual.readMarketImportHistory(window,await(await fetch('actual-catalog.json')).json()));const before=await history();
phase='EMPTY';for(const input of ['', ' \t\n \r\n']){await root.locator('[data-sheet-paste]').fill(input);await root.locator('[data-sheet-action="paste"]').click();await root.locator('[data-sheet-notice][data-notice="emptyPaste"]').waitFor();assert.equal(await root.locator('[data-sheet-notice]').textContent(),locale==='en-US'?'There is no content to paste.':'붙여넣을 내용이 없습니다');assert.deepEqual(await history(),before);}
assert.equal(await page.evaluate(()=>window.__importWrites),0);assert.equal(await page.evaluate(()=>window.__importChanges),0);
phase='VALID';await root.locator('[data-sheet-paste]').fill('code\tprice\ttradetime\nNASDAQ:NVDA\t111.125\t'+new Date().toISOString());await root.locator('[data-sheet-action="paste"]').click();await page.waitForFunction(()=>document.querySelector('[data-sheet-summary]')?.dataset.successCount==='1');const after=await history();assert.equal(after.length,before.length+1);assert.equal(after.at(-1).method,'paste');assert.equal(await root.locator('[data-sheet-paste]').inputValue(),'');assert.ok((await root.locator('[data-sheet-history]').textContent()).includes(locale==='en-US'?'Paste':'붙여넣기'));
phase='AFTER_SAVE_EMPTY';await root.locator('[data-sheet-action="paste"]').click();await root.locator('[data-sheet-notice][data-notice="emptyPaste"]').waitFor();assert.deepEqual(await history(),after);assert.equal(await page.evaluate(()=>window.__importWrites),1);assert.equal(await page.evaluate(()=>window.__importChanges),1);
phase='RELOAD';await page.reload();await root.locator('[data-sheet-paste]').waitFor({state:'attached'});assert.equal(await advanced.getAttribute('open'),null);assert.deepEqual(await history(),after);assert.equal(external,0);assert.equal(errors,0);assert.equal(await page.evaluate(()=>window.__importCsp),0);assert.ok(await page.evaluate(()=>document.documentElement.scrollWidth<=innerWidth));pass++;console.log('PASS advanced imports and empty no-op '+width+' '+locale);await context.close();}
}catch(_){fail++;console.log('FAIL settings imports '+phase);}finally{await browser.close();}console.log('COUNTS pass='+pass+' fail='+fail);if(fail)process.exitCode=1;})();
