"""Static News | Network page for one ``RIGViewModel``. NEW IMPLEMENTATION.

The page swaps the whole content area between News and Network (no side-by-side
split). Zoom (wheel/pinch), pan (drag on empty space), node drag, node/edge quick
view, double-click focus, ``+N`` expansion, fit and search run client-side over
the embedded, already-projected model; the page never fetches or scores anything.
Later phases add presentation through ``PageExtras`` without editing this module.
"""

from __future__ import annotations

import html
import json
from dataclasses import dataclass, field

from .labels import TERMS, Language, term
from .views import RIGViewModel, ViewKind


@dataclass(frozen=True)
class PageExtras:
    card_badges: dict = field(default_factory=dict)  # event_id -> tuple[str, ...] (term keys)
    edge_badges: dict = field(default_factory=dict)  # relationship_id -> tuple[str, ...] (term keys, max 2 shown)
    edge_width: dict = field(default_factory=dict)  # relationship_id -> float
    node_symbol: dict = field(default_factory=dict)  # node_id -> symbol
    toolbar_html: str = ""  # trusted, generated by later RIG phases only
    terms: dict = field(default_factory=dict)  # key -> (en, ko)
    card_order: tuple = ()  # optional event_id order (feed priority); default = model order


MAX_EDGE_BADGES = 2

CSS = """
:root{--ink:#14202b;--paper:#f3eee4;--card:#fffdf8;--line:#d8cfc0;--acc:#1d4f61;--muted:#5b6770}
@media (prefers-color-scheme:dark){:root:not([data-theme=light]){--ink:#e6e1d6;--paper:#161c21;--card:#1f272d;
--line:#39444c;--acc:#7fb6c7;--muted:#9aa6ad}}
*{box-sizing:border-box}body{margin:0;font-family:Georgia,"Iowan Old Style",serif;background:var(--paper);color:var(--ink)}
header{padding:16px;display:flex;flex-wrap:wrap;gap:8px;align-items:center;border-bottom:1px solid var(--line)}
header h1{font-size:20px;margin:0 12px 0 0}.seg button{border:1px solid var(--ink);background:none;color:var(--ink);
padding:4px 12px;font:inherit;cursor:pointer}.seg button[aria-pressed=true]{background:var(--ink);color:var(--paper)}
.tb{display:flex;gap:6px;flex-wrap:wrap;align-items:center;font-size:13px}.tb>*{font:inherit}
main{padding:12px 16px}.card{background:var(--card);border:1px solid var(--line);padding:12px;margin:0 0 10px}
.card h3{margin:4px 0;font-size:16px}.meta{color:var(--muted);font-size:12px}
.badge{display:inline-block;border:1px solid var(--ink);font-size:11px;padding:1px 6px;margin-right:4px}
#net{color:var(--ink);width:100%;height:70vh;background:var(--card);border:1px solid var(--line);touch-action:none;display:block}
#net text{fill:var(--ink);font-size:13px}#net line{stroke:var(--ink)}#net .inf{stroke-dasharray:6 5}
#net circle{fill:var(--card);stroke:var(--acc);stroke-width:2;cursor:grab}#net .hidden{display:none}
#qv{background:var(--card);border:1px solid var(--line);padding:10px;margin-top:8px;font-size:13px;min-height:2em}
.note{color:var(--muted);font-size:12px}
"""

JS = r"""
const M=JSON.parse(document.getElementById('rig-data').textContent);
let lang=M.lang,vp={...M.viewport},focus=M.focus,steps=M.steps,view=M.view;
const T=k=>{const t=M.terms[k];if(!t)return k;return lang==='EN'?t[0]:lang==='KO'?t[1]:(t[0]===t[1]?t[0]:t[0]+' ('+t[1]+')')};
function relabel(){document.querySelectorAll('[data-term]').forEach(e=>{e.textContent=(e.dataset.prefix||'')+T(e.dataset.term)});
 document.getElementById('q').placeholder=T('search')}
function show(v){view=v;for(const k of ['NEWS','NETWORK']){document.getElementById('pane-'+k).hidden=k!==v;
 document.querySelector('[data-view='+k+']').setAttribute('aria-pressed',k===v)}}
const svg=document.getElementById('net'),g=document.getElementById('vp');
function apply(){g.setAttribute('transform',`translate(${vp.pan_x} ${vp.pan_y}) scale(${vp.zoom})`)}
const pos={};M.nodes.forEach(n=>pos[n.id]={x:n.x,y:n.y});
function redraw(){M.edges.forEach(e=>{const l=document.getElementById('e-'+e.id),a=pos[e.s],b=pos[e.t];
 l.setAttribute('x1',a.x);l.setAttribute('y1',a.y);l.setAttribute('x2',b.x);l.setAttribute('y2',b.y)});
 M.nodes.forEach(n=>{const c=document.getElementById('n-'+n.id);c.setAttribute('transform',`translate(${pos[n.id].x} ${pos[n.id].y})`)})}
function visible(){const vis=new Set(),ns=new Set();let hidden=M.hidden;
 if(focus){const ord=M.order[focus]||[];const k=M.limit*(1+steps);ord.slice(0,k).forEach(r=>vis.add(r));hidden=Math.max(0,ord.length-k);ns.add(focus)}
 else M.edges.forEach(e=>vis.add(e.id));
 M.edges.forEach(e=>{const on=vis.has(e.id);document.getElementById('e-'+e.id).classList.toggle('hidden',!on);if(on){ns.add(e.s);ns.add(e.t)}});
 M.nodes.forEach(n=>document.getElementById('n-'+n.id).classList.toggle('hidden',!ns.has(n.id)));
 const b=document.getElementById('more');b.hidden=hidden===0;b.querySelector('[data-term]').dataset.prefix='+'+hidden+' ';relabel()}
function zoomAt(f,cx,cy){const z=Math.min(5,Math.max(0.2,vp.zoom*f));const k=z/vp.zoom;vp.pan_x=cx-(cx-vp.pan_x)*k;vp.pan_y=cy-(cy-vp.pan_y)*k;vp.zoom=z;apply()}
function pt(ev){const r=svg.getBoundingClientRect();return{x:(ev.clientX-r.left)*1000/r.width,y:(ev.clientY-r.top)*1000/r.height}}
svg.addEventListener('wheel',ev=>{ev.preventDefault();const p=pt(ev);zoomAt(ev.deltaY<0?1.15:1/1.15,p.x,p.y)},{passive:false});
let drag=null;const pts=new Map();
svg.addEventListener('pointerdown',ev=>{pts.set(ev.pointerId,pt(ev));const n=ev.target.closest('[data-node]');const p=pt(ev);
 drag=n?{node:n.dataset.node,p}:{pan:true,p,vx:vp.pan_x,vy:vp.pan_y};
 if(!n)svg.setPointerCapture(ev.pointerId)});  // node presses keep their click/dblclick target
svg.addEventListener('pointermove',ev=>{if(!drag)return;const p=pt(ev);
 if(pts.size===2){const [a,b]=[...pts.values()];const d0=Math.hypot(a.x-b.x,a.y-b.y);pts.set(ev.pointerId,p);
  const [c,d]=[...pts.values()];const d1=Math.hypot(c.x-d.x,c.y-d.y);if(d0>0)zoomAt(d1/d0,(c.x+d.x)/2,(c.y+d.y)/2);return}
 pts.set(ev.pointerId,p);
 if(drag.node){pos[drag.node].x+=(p.x-drag.p.x)/vp.zoom;pos[drag.node].y+=(p.y-drag.p.y)/vp.zoom;drag.p=p;drag.moved=true;redraw()}
 else{vp.pan_x=drag.vx+(p.x-drag.p.x);vp.pan_y=drag.vy+(p.y-drag.p.y);apply()}});
svg.addEventListener('pointerup',ev=>{pts.delete(ev.pointerId);drag=null});
const qv=document.getElementById('qv');
function quickNode(id){const n=M.nodes.find(x=>x.id===id);const c=M.edges.filter(e=>e.s===id||e.t===id).length;
 qv.textContent=`${T('company')}: ${n.label} · ${n.issuer} · ${c} ${T('relationship')}`}
function quickEdge(id){const e=M.edges.find(x=>x.id===id);
 qv.textContent=`${T('relationship')}: ${T(e.type)} · ${T(e.ep)} · ${T('available_at')} ${e.at} · ${T('last_confirmed_at')} ${e.lc}`}
svg.addEventListener('click',ev=>{const n=ev.target.closest('[data-node]'),e=ev.target.closest('[data-edge]');
 if(n)quickNode(n.dataset.node);else if(e)quickEdge(e.dataset.edge)});
svg.addEventListener('dblclick',ev=>{const n=ev.target.closest('[data-node]');if(n){focus=n.dataset.node;steps=0;visible()}});
document.getElementById('more').onclick=()=>{steps+=1;visible()};
document.getElementById('fit').onclick=()=>{vp={zoom:1,pan_x:0,pan_y:0};focus=null;steps=0;apply();visible()};
document.getElementById('q').addEventListener('change',ev=>{const s=ev.target.value.trim().toLowerCase();
 const n=M.nodes.find(x=>x.label.toLowerCase().includes(s)||x.issuer.toLowerCase()===s);if(n){focus=n.id;steps=0;visible();quickNode(n.id)}});
document.querySelectorAll('[data-view]').forEach(b=>b.onclick=()=>show(b.dataset.view));
document.getElementById('lang').onchange=ev=>{lang=ev.target.value;relabel()};
window.rigState=()=>({view,focus,steps,viewport:{...vp},lang});
show(view);apply();redraw();visible();
"""


def _e(s) -> str:
    return html.escape(str(s), quote=True)


def _t(key: str, lang: Language, extras: PageExtras, prefix: str = "") -> str:
    return (f'<span data-term="{_e(key)}" data-prefix="{_e(prefix)}">'
            f'{_e(prefix + term(key, lang, extras.terms))}</span>')


def render_page(vm: RIGViewModel, lang: Language = Language.KO, extras: PageExtras | None = None) -> str:
    x = extras or PageExtras()
    net = vm.network
    names = {n.issuer_id: n.label for n in net.nodes}
    cards = {c.event_id: c for c in vm.cards}
    order = [i for i in x.card_order if i in cards] + [c.event_id for c in vm.cards if c.event_id not in x.card_order]
    card_html = []
    for eid in order:
        c = cards[eid]
        badges = "".join(f'<span class="badge">{_t(b, lang, x)}</span>' for b in (c.status.value,) + tuple(
            x.card_badges.get(eid, ())))
        who = ", ".join(_e(names.get(i, i)) for i in c.issuer_ids)
        summary = "".join(f"<p>{_e(s)}</p>" for s in c.summary)
        card_html.append(
            f'<article class="card" data-event="{_e(eid)}">{badges}<h3>{_e(c.headline)}</h3>'
            f'<div class="meta">{who} · {_e(c.available_at.isoformat())} · {c.source_count} {_t("sources", lang, x)}</div>'
            f'{summary}<details><summary>{_t("more", lang, x)}</summary><div class="meta">'
            f'{_e(" ".join(c.relationship_ids))}</div><p class="note">{_t("evidence_note", lang, x)}</p></details></article>')
    if not card_html:
        card_html.append(f'<p class="note">{_t("no_news", lang, x)}</p>')
    pos = {n.node_id: n for n in net.nodes}
    svg = ['<defs><marker id="arr" viewBox="0 0 10 10" refX="22" refY="5" markerWidth="7" markerHeight="7" '
           'orient="auto-start-reverse"><path d="M0,0L10,5L0,10z" fill="currentColor"/></marker></defs><g id="vp">']
    for ed in net.edges:
        a, b = pos[ed.source_node_id], pos[ed.target_node_id]
        cls = "inf" if ed.line == "DASHED" else "fact"
        width = x.edge_width.get(ed.relationship_id, 1.5)
        badges = tuple(x.edge_badges.get(ed.relationship_id, ()))[:MAX_EDGE_BADGES]
        title = " · ".join([term(ed.relationship_type.value, lang, x.terms), term(ed.epistemic.value, lang, x.terms)]
                           + [term(k, lang, x.terms) for k in badges])
        marker = ' marker-end="url(#arr)"' if ed.arrow else ""
        svg.append(
            f'<line id="e-{_e(ed.relationship_id)}" data-edge="{_e(ed.relationship_id)}" class="{cls}" '
            f'x1="{a.x}" y1="{a.y}" x2="{b.x}" y2="{b.y}" stroke-width="{width}"{marker}><title>{_e(title)}</title></line>')
    for n in net.nodes:
        sym = x.node_symbol.get(n.node_id, n.symbol)
        svg.append(f'<g id="n-{_e(n.node_id)}" data-node="{_e(n.node_id)}" transform="translate({n.x} {n.y})">'
                   f'<circle r="16"/><text text-anchor="middle" dy="5">{_e(sym)}</text>'
                   f'<text text-anchor="middle" dy="36">{_e(n.label)}</text></g>')
    svg.append("</g>")
    data = {
        "lang": lang.value, "view": vm.state.view.value, "focus": vm.state.focus_node_id,
        "steps": vm.state.expansion_steps, "limit": 8, "hidden": net.hidden_edge_count,
        "viewport": {"zoom": vm.state.viewport.zoom, "pan_x": vm.state.viewport.pan_x,
                     "pan_y": vm.state.viewport.pan_y},
        "terms": {**TERMS, **x.terms},
        "nodes": [{"id": n.node_id, "issuer": n.issuer_id, "label": n.label, "x": n.x, "y": n.y} for n in net.nodes],
        "edges": [{"id": e.relationship_id, "s": e.source_node_id, "t": e.target_node_id,
                   "type": e.relationship_type.value, "ep": e.epistemic.value, "at": e.available_at.isoformat(),
                   "lc": e.last_confirmed_at.isoformat()} for e in net.edges],
        "order": net.neighbor_order,
    }
    payload = json.dumps(data, ensure_ascii=False, sort_keys=True).replace("</", "<\\/")
    opts = "".join(f'<option value="{l.value}"{" selected" if l is lang else ""}>{v}</option>'
                   for l, v in ((Language.EN, "English"), (Language.EN_KO, "English (한국어)"), (Language.KO, "한국어")))
    return f"""<!DOCTYPE html>
<html lang="ko"><head><meta charset="utf-8"><meta name="viewport" content="width=device-width, initial-scale=1">
<title>RIG News Network</title><style>{CSS}</style></head><body>
<header><h1>{_t("news", lang, x)}</h1>
<div class="seg" role="group"><button data-view="NEWS">{_t("news", lang, x)}</button><button data-view="NETWORK">{_t("network", lang, x)}</button></div>
<div class="tb">{x.toolbar_html}<select id="lang" aria-label="language">{opts}</select>
<span class="meta">{_t("as_of", lang, x)} {_e(vm.graph_as_of.isoformat())}</span></div></header>
<main><section id="pane-NEWS">{"".join(card_html)}</section>
<section id="pane-NETWORK" hidden><div class="tb"><input id="q" type="search">
<button id="fit" title="fit">⌂ {_t("fit", lang, x)}</button><button id="more" hidden>{_t("more_relationships", lang, x)}</button></div>
<svg id="net" viewBox="0 0 1000 1000" role="img" aria-label="network">{"".join(svg)}</svg><div id="qv"></div></section></main>
<script type="application/json" id="rig-data">{payload}</script><script>{JS}</script></body></html>"""
