/* #146 canonical Python port. Pure RAM-only research; no persistence or provider. */
(function(root,factory){const api=factory(typeof module==='object'&&module.exports?require('./profile-defaults.js'):root.ProfileDefaults);if(typeof module==='object'&&module.exports)module.exports=api;else root.EnginePreview=api;})(globalThis,function(defaults){
'use strict';const finite=v=>typeof v==='number'&&Number.isFinite(v),object=v=>v!==null&&typeof v==='object'&&!Array.isArray(v),safe=v=>finite(v)&&(!Number.isInteger(v)||Number.isSafeInteger(v));
function dcfResult(reason=null,value=null,flows=null,growth=null){return{state:reason?'NOT_AVAILABLE':'PROVISIONAL',reason_codes:reason?[reason]:[],value_per_share:value,discounted_cashflows:flows,implied_growth:growth,role:'RAM_ONLY_RESEARCH',model_status:'NOT_APPLIED'};}
function parameters(p,currency,priceCurrency){if(!object(p))return 'PARAMETER_INVALID';if(p.confirmed!==true)return 'PARAMETER_APPROVAL_PENDING';if(!Number.isInteger(p.explicit_years)||p.explicit_years<1||p.explicit_years>100||!finite(p.discount_rate)||!finite(p.terminal_growth)||p.discount_rate<=-1||p.terminal_growth<=-1)return'PARAMETER_INVALID';if(p.discount_rate<=p.terminal_growth)return'GORDON_RATE_ORDER';if(p.cashflow_basis!=='FCFE_PER_SHARE'||p.discount_rate_basis!=='COST_OF_EQUITY')return'CASHFLOW_BASIS_UNCONFIRMED';if(p.per_share_basis_confirmed!==true)return'SHARE_BASIS_UNCONFIRMED';if(!['USD','KRW','JPY'].includes(p.currency)||currency!==p.currency||(arguments.length>=3&&priceCurrency!==p.currency))return'CURRENCY_BASIS_UNCONFIRMED';return null;}
function compensated(values){let sum=0,error=0;for(const value of values){const next=sum+value;error+=Math.abs(sum)>=Math.abs(value)?(sum-next)+value:(value-next)+sum;sum=next;}return sum+error;}
function compute(cashflow,growth,p){const flows=[];for(let t=1;t<=p.explicit_years;t++)flows.push(cashflow*Math.pow(1+growth,t)/Math.pow(1+p.discount_rate,t));const terminal=cashflow*Math.pow(1+growth,p.explicit_years)*(1+p.terminal_growth)/(p.discount_rate-p.terminal_growth)/Math.pow(1+p.discount_rate,p.explicit_years),value=compensated([...flows,terminal]);if(![...flows,terminal,value].every(finite))throw Error('NUMERIC_OVERFLOW');return{value,flows};}
function dcf({cashflow_per_share,growth_rate,parameters:p,cashflow_currency}={}){const reason=parameters(p,cashflow_currency);if(reason)return dcfResult(reason);if(!safe(cashflow_per_share)||!finite(growth_rate)||growth_rate<=-1)return dcfResult('INPUT_INVALID');try{const r=compute(cashflow_per_share,growth_rate,p);return dcfResult(null,r.value,r.flows);}catch(_){return dcfResult('NUMERIC_OVERFLOW');}}
function reverseDcf({cashflow_per_share,price,parameters:p,cashflow_currency,price_currency}={}){const reason=parameters(p,cashflow_currency,price_currency);if(reason)return dcfResult(reason);if(!safe(cashflow_per_share)||!safe(price)||price<=0)return dcfResult('INPUT_INVALID');if(cashflow_per_share<=0)return dcfResult('NON_POSITIVE_CASHFLOW');const s=p.solver;if(!object(s))return dcfResult('SOLVER_INVALID');let lower=s.growth_lower,upper=s.growth_upper;const tol=s.relative_price_tolerance,limit=s.maximum_iterations;if(!finite(lower)||!finite(upper)||!(-1<lower&&lower<upper)||!finite(tol)||!(tol>0&&tol<1)||!Number.isInteger(limit)||limit<1||limit>10000)return dcfResult('SOLVER_INVALID');try{const low=compute(cashflow_per_share,lower,p).value,high=compute(cashflow_per_share,upper,p).value;for(const [endpoint,value]of [[lower,low],[upper,high]])if(Math.abs(value/price-1)<=tol)return dcfResult(null,null,null,endpoint);if(!(low<price&&price<high))return dcfResult('ROOT_NOT_BRACKETED');for(let i=0;i<limit;i++){const mid=lower/2+upper/2,value=compute(cashflow_per_share,mid,p).value;if(Math.abs(value/price-1)<=tol)return dcfResult(null,null,null,mid);if(value<price)lower=mid;else upper=mid;}}catch(_){return dcfResult('NUMERIC_OVERFLOW');}return dcfResult('ROOT_NOT_CONVERGED');}
const missing=reason=>({score:null,state:'NOT_AVAILABLE',reason}),clip=x=>{if(!finite(x))throw Error('CALCULATION_ERROR');return Math.max(0,Math.min(100,x));},checked=x=>{if(!finite(x))throw Error('CALCULATION_ERROR');return x;};
function calc(fn){try{const v=fn();return v===null?missing('MISSING_INPUT'):{score:clip(v),state:'CALCULATED',reason:'APPROVED_V1_MAPPING'};}catch(_){return missing('CALCULATION_ERROR');}}
function priceReason(i,p){return p===null||p===undefined?'MISSING_PRICE':!safe(p)||p<=0?'INVALID_PRICE':i.basis_confirmed!==true?'BASIS_UNCONFIRMED':null;}
function intrinsic(i,p,mos){const reason=priceReason(i,p);if(reason)return missing(reason);const d=i.dcf_value;if(d!==null&&d!==undefined&&!safe(d))return missing('INVALID_INPUT');if(d)return calc(()=>mos?50+checked(checked(checked(.75*d)/p)-1)/.3*50:50+checked(checked(d/p)-1)/.4*50);const eps=i.eps;if(eps!==null&&eps!==undefined&&!safe(eps))return missing('INVALID_INPUT');if(eps===null||eps===undefined||eps<=0)return missing('MISSING_INPUT');return calc(()=>mos?50+checked(checked(checked(12*eps)/p)-1)/.3*50:50+checked(20-checked(p/eps))/20*50);}
function reverseFactor(i,p){let implied=i.reverse_dcf_implied_growth;if(implied!==null&&implied!==undefined){if(!safe(implied))return missing('INVALID_INPUT');}else{const reason=priceReason(i,p);if(reason)return missing(reason);const eps=i.eps;if(eps!==null&&eps!==undefined&&!safe(eps))return missing('INVALID_INPUT');if(eps===null||eps===undefined||eps<=0)return missing('MISSING_INPUT');try{implied=Math.max(-.2,Math.min(.4,checked(checked(checked(p/eps)-15)/100)));}catch(_){return missing('CALCULATION_ERROR');}}const r=i.revenue,prev=i.revenue_prev;if([r,prev].some(v=>v!==null&&v!==undefined&&!safe(v)))return missing('INVALID_INPUT');if(r===null||r===undefined||prev===null||prev===undefined||prev===0)return missing('MISSING_INPUT');return calc(()=>50+checked(checked(checked(checked(r/prev)-1)-implied)/.15)*50);}
function passthrough(v){return v===null||v===undefined?missing('UNDEFINED_PRICE_MAPPING'):!finite(v)||v<0||v>100?missing('INVALID_INPUT'):{score:v,state:'PASSTHROUGH',reason:'SUPPLIED_SCORE'};}
function vFactors({inputs:i={},price=null}={}){const own=i.own_multiple,peer=i.peer_median_multiple;const peerResult=[own,peer].some(v=>v!==null&&v!==undefined&&!safe(v))?missing('INVALID_INPUT'):!own||!peer?missing('MISSING_INPUT'):calc(()=>50+checked(checked(checked(peer-own)/peer)/.3)*50);return{factors:{fundamental_value:intrinsic(i,price,false),peer_relative_value:peerResult,historical_valuation:passthrough(i.hist_valuation_percentile),sector_context:passthrough(i.sector_context_score),theme_premium_discount:passthrough(i.theme_premium_score),reverse_dcf:reverseFactor(i,price),margin_of_safety:intrinsic(i,price,true)},role:'RAM_ONLY_V1',standard:'v1',calibration:'UNCALIBRATED',standard_status:'STANDARD v1 · UNCALIBRATED',undefined_price_definitions:['DCF_SOLVER','REVERSE_DCF_SOLVER','OWN_MULTIPLE_PRICE_MAPPING','HISTORICAL_VALUATION_PRICE_MAPPING','SECTOR_CONTEXT_PRICE_MAPPING','THEME_PRICE_MAPPING']};}
function roundEven(x,digits=4){if(x===0)return x;const buffer=new ArrayBuffer(8),view=new DataView(buffer);view.setFloat64(0,Math.abs(x));const bits=view.getBigUint64(0),exp=Number((bits>>52n)&2047n)-1023-52,frac=(bits&((1n<<52n)-1n))+(1n<<52n);let n=frac*10n**BigInt(digits),d=1n;if(exp>=0)n<<=BigInt(exp);else d<<=BigInt(-exp);let q=n/d;const rem=n%d;if(rem*2n>d||rem*2n===d&&q%2n)q++;return (x<0?-1:1)*Number(q)/10**digits;}
function strategy({observations={},user_weights=null,profile_kind='GENERAL_CORPORATE'}={}){try{if(!object(observations)||!['GENERAL_CORPORATE','FINANCIAL'].includes(profile_kind))throw Error();const validQualities=['OK','SYNTHETIC','MISSING_DATA','BLOCKED_DEPENDENCY','PIT_UNAVAILABLE','NOT_APPLICABLE','STALE_DATA','ESTIMATED_DATA','CONFLICTING_SOURCE','VERSION_MISMATCH','IDENTIFIER_CHANGED','CALCULATION_ERROR','IDENTIFIER_AMBIGUOUS'];for(const o of Object.values(observations))if(!object(o)||!validQualities.includes(o.quality)||o.score!==null&&(!finite(o.score)||o.score<0||o.score>100))throw Error();const official=structuredClone(defaults.weights),effective=structuredClone(official);if(user_weights!==null){if(!object(user_weights))throw Error();for(const[axis,w]of Object.entries(user_weights)){if(!Object.hasOwn(effective,axis)||!object(w))throw Error();for(const[f,v]of Object.entries(w)){if(!Object.hasOwn(effective[axis],f)||!finite(v)||v<0||v>100)throw Error();effective[axis][f]=v;}}}const axes={};for(const [axis,ws]of Object.entries(effective)){if(Math.abs(Object.values(ws).reduce((a,b)=>a+b,0)-100)>defaults.sum_tolerance)throw Error();let used=0,acc=0,blocked=false,missingAny=false;const missingIds=[],notApplicable=[];for(const[f,w]of Object.entries(ws)){if(profile_kind==='FINANCIAL'&&f==='roic_wacc'){notApplicable.push(f);continue;}const o=observations[f],available=o&&o.score!==null&&!['MISSING_DATA','BLOCKED_DEPENDENCY','PIT_UNAVAILABLE','NOT_APPLICABLE'].includes(o.quality);if(!available)missingIds.push(f);if(!o){missingAny=true;continue;}if(o.quality==='BLOCKED_DEPENDENCY'){blocked=true;continue;}if(!available){missingAny=true;continue;}acc+=(w/100)*o.score;used+=w/100;}axes[axis]={score:blocked||used===0?null:acc,coverage:blocked||used===0?'BLOCKED':missingAny||used<1-1e-12?'PARTIAL':'READY',missing_factor_ids:missingIds,not_applicable_ids:notApplicable,missing_factor_count:missingIds.length};}return{axes,qg_preview_total:axes.Q.score===null||axes.G.score===null?null:roundEven((axes.Q.score+axes.G.score)/2,4),official_weights:official,effective_weights:effective,role:'PREVIEW',parent_mix_note:'UNDEFINED_PARENT_WEIGHTS'};}catch(_){return{state:'INVALID_INPUT'};}}
function companyTypes(){return{state:'DEPENDENCY_PENDING',reason:'TYPE_ENGINE_PENDING_MERGE'};}
return Object.freeze({dcf,reverseDcf,vFactors,strategy,companyTypes,roundEven});
});
