/* #146 canonical Python port. Pure RAM-only research; no persistence or provider. */
(function(root,factory){const api=factory(typeof module==='object'&&module.exports?require('./profile-defaults.js'):root.ProfileDefaults);if(typeof module==='object'&&module.exports)module.exports=api;else root.EnginePreview=api;})(globalThis,function(defaults){
'use strict';const finite=v=>typeof v==='number'&&Number.isFinite(v),object=v=>v!==null&&typeof v==='object'&&!Array.isArray(v),safe=v=>finite(v)&&(!Number.isInteger(v)||Number.isSafeInteger(v));
function dcfResult(reason=null,value=null,flows=null,growth=null){return{state:reason?'NOT_AVAILABLE':'PROVISIONAL',reason_codes:reason?[reason]:[],value_per_share:value,discounted_cashflows:flows,implied_growth:growth,role:'RAM_ONLY_RESEARCH',model_status:'NOT_APPLIED'};}
function parameters(p,currency,priceCurrency){if(!object(p))return 'PARAMETER_INVALID';if(p.confirmed!==true)return 'PARAMETER_APPROVAL_PENDING';if(!Number.isInteger(p.explicit_years)||p.explicit_years<1||p.explicit_years>100||!finite(p.discount_rate)||!finite(p.terminal_growth)||p.discount_rate<=-1||p.terminal_growth<=-1)return'PARAMETER_INVALID';if(p.discount_rate<=p.terminal_growth)return'GORDON_RATE_ORDER';if(p.cashflow_basis!=='FCFE_PER_SHARE'||p.discount_rate_basis!=='COST_OF_EQUITY')return'CASHFLOW_BASIS_UNCONFIRMED';if(p.per_share_basis_confirmed!==true)return'SHARE_BASIS_UNCONFIRMED';if(!['USD','KRW','JPY'].includes(p.currency)||currency!==p.currency||(arguments.length>=3&&priceCurrency!==p.currency))return'CURRENCY_BASIS_UNCONFIRMED';return null;}
function compensated(values){let sum=0,error=0;for(const value of values){const next=sum+value;error+=Math.abs(sum)>=Math.abs(value)?(sum-next)+value:(value-next)+sum;sum=next;}return sum+error;}
function compute(cashflow,growth,p){const flows=[];for(let t=1;t<=p.explicit_years;t++)flows.push(cashflow*Math.pow(1+growth,t)/Math.pow(1+p.discount_rate,t));const terminal=cashflow*Math.pow(1+growth,p.explicit_years)*(1+p.terminal_growth)/(p.discount_rate-p.terminal_growth)/Math.pow(1+p.discount_rate,p.explicit_years),value=compensated([...flows,terminal]);if(![...flows,terminal,value].every(finite))throw Error('NUMERIC_OVERFLOW');return{value,flows};}
function dcf({cashflow_per_share,growth_rate,parameters:p,cashflow_currency}={}){const reason=parameters(p,cashflow_currency);if(reason)return dcfResult(reason);if(!safe(cashflow_per_share)||!finite(growth_rate)||growth_rate<=-1)return dcfResult('INPUT_INVALID');try{const r=compute(cashflow_per_share,growth_rate,p);return dcfResult(null,r.value,r.flows);}catch(_){return dcfResult('NUMERIC_OVERFLOW');}}
function reverseDcf({cashflow_per_share,price,parameters:p,cashflow_currency,price_currency}={}){const reason=parameters(p,cashflow_currency,price_currency);if(reason)return dcfResult(reason);if(!safe(cashflow_per_share)||!safe(price)||price<=0)return dcfResult('INPUT_INVALID');if(cashflow_per_share<=0)return dcfResult('NON_POSITIVE_CASHFLOW');const s=p.solver;if(!object(s))return dcfResult('SOLVER_INVALID');let lower=s.growth_lower,upper=s.growth_upper;const tol=s.relative_price_tolerance,limit=s.maximum_iterations;if(!finite(lower)||!finite(upper)||!(-1<lower&&lower<upper)||!finite(tol)||!(tol>0&&tol<1)||!Number.isInteger(limit)||limit<1||limit>10000)return dcfResult('SOLVER_INVALID');try{const low=compute(cashflow_per_share,lower,p).value,high=compute(cashflow_per_share,upper,p).value;for(const [endpoint,value]of [[lower,low],[upper,high]])if(Math.abs(value/price-1)<=tol)return dcfResult(null,null,null,endpoint);if(!(low<price&&price<high))return dcfResult('ROOT_NOT_BRACKETED');for(let i=0;i<limit;i++){const mid=lower/2+upper/2,value=compute(cashflow_per_share,mid,p).value;if(Math.abs(value/price-1)<=tol)return dcfResult(null,null,null,mid);if(value<price)lower=mid;else upper=mid;}}catch(_){return dcfResult('NUMERIC_OVERFLOW');}return dcfResult('ROOT_NOT_CONVERGED');}
const missing=reason=>({score:null,state:'NOT_AVAILABLE',reason}),clip=x=>{if(!finite(x))throw Error('CALCULATION_ERROR');return Math.max(0,Math.min(100,x));},checked=x=>{if(!finite(x))throw Error('CALCULATION_ERROR');return x;};
function calc(fn){try{const v=fn();return v===null?missing('MISSING_INPUT'):{score:clip(v),state:'CALCULATED',reason:'APPROVED_V1_MAPPING'};}catch(_){return missing('CALCULATION_ERROR');}}
function priceReason(i,p){return p===null||p===undefined?'MISSING_PRICE':!safe(p)||p<=0?'INVALID_PRICE':i.basis_confirmed!==true?'BASIS_UNCONFIRMED':null;}
function intrinsic(i,p,mos){const reason=priceReason(i,p);if(reason)return missing(reason);const d=i.dcf_value;if(d!==null&&d!==undefined&&!safe(d))return missing('INVALID_INPUT');if(d)return calc(()=>mos?50+checked(checked(checked(.75*d)/p)-1)/.3*50:50+checked(checked(d/p)-1)/.4*50);const eps=i.eps;if(eps!==null&&eps!==undefined&&!safe(eps))return missing('INVALID_INPUT');if(eps===null||eps===undefined||eps<=0)return missing('MISSING_INPUT');return calc(()=>mos?50+checked(checked(checked(12*eps)/p)-1)/.3*50:50+checked(20-checked(p/eps))/20*50);}
function reverseFactor(i,p){let implied=i.reverse_dcf_implied_growth;if(implied!==null&&implied!==undefined){if(!safe(implied))return missing('INVALID_INPUT');}else{const reason=priceReason(i,p);if(reason)return missing(reason);const eps=i.eps;if(eps!==null&&eps!==undefined&&!safe(eps))return missing('INVALID_INPUT');if(eps===null||eps===undefined||eps<=0)return missing('MISSING_INPUT');try{implied=Math.max(-.2,Math.min(.4,checked(checked(checked(p/eps)-15)/100)));}catch(_){return missing('CALCULATION_ERROR');}}const r=i.revenue,prev=i.revenue_prev;if([r,prev].some(v=>v!==null&&v!==undefined&&!safe(v)))return missing('INVALID_INPUT');if(r===null||r===undefined||prev===null||prev===undefined||prev===0)return missing('MISSING_INPUT');return calc(()=>50+checked(checked(checked(checked(r/prev)-1)-implied)/.15)*50);}
function passthrough(v){return v===null||v===undefined?missing('UNDEFINED_PRICE_MAPPING'):!finite(v)||v<0||v>100?missing('INVALID_INPUT'):{score:v,state:'PASSTHROUGH',reason:'SUPPLIED_SCORE'};}
function vFactors({inputs:i={},price=null}={}){const own=i.own_multiple,peer=i.peer_median_multiple;const peerResult=[own,peer].some(v=>v!==null&&v!==undefined&&!safe(v))?missing('INVALID_INPUT'):!own||!peer?missing('MISSING_INPUT'):calc(()=>50+checked(checked(checked(peer-own)/peer)/.3)*50);return{factors:{fundamental_value:intrinsic(i,price,false),peer_relative_value:peerResult,historical_valuation:passthrough(i.hist_valuation_percentile),sector_context:passthrough(i.sector_context_score),theme_premium_discount:passthrough(i.theme_premium_score),reverse_dcf:reverseFactor(i,price),margin_of_safety:intrinsic(i,price,true)},role:'RAM_ONLY_V1',standard:'v1',calibration:'UNCALIBRATED',standard_status:'STANDARD v1 · UNCALIBRATED',undefined_price_definitions:['DCF_SOLVER','REVERSE_DCF_SOLVER','OWN_MULTIPLE_PRICE_MAPPING','HISTORICAL_VALUATION_PRICE_MAPPING','SECTOR_CONTEXT_PRICE_MAPPING','THEME_PRICE_MAPPING']};}
function roundEven(x,digits=4){if(x===0)return x;const buffer=new ArrayBuffer(8),view=new DataView(buffer);view.setFloat64(0,Math.abs(x));const bits=view.getBigUint64(0),exp=Number((bits>>52n)&2047n)-1023-52,frac=(bits&((1n<<52n)-1n))+(1n<<52n);let n=frac*10n**BigInt(digits),d=1n;if(exp>=0)n<<=BigInt(exp);else d<<=BigInt(-exp);let q=n/d;const rem=n%d;if(rem*2n>d||rem*2n===d&&q%2n)q++;return (x<0?-1:1)*Number(q)/10**digits;}
function strategy({observations={},user_weights=null,profile_kind='GENERAL_CORPORATE'}={}){try{if(!object(observations)||!['GENERAL_CORPORATE','FINANCIAL'].includes(profile_kind))throw Error();const validQualities=['OK','SYNTHETIC','MISSING_DATA','BLOCKED_DEPENDENCY','PIT_UNAVAILABLE','NOT_APPLICABLE','STALE_DATA','ESTIMATED_DATA','CONFLICTING_SOURCE','VERSION_MISMATCH','IDENTIFIER_CHANGED','CALCULATION_ERROR','IDENTIFIER_AMBIGUOUS'];for(const o of Object.values(observations))if(!object(o)||!validQualities.includes(o.quality)||o.score!==null&&(!finite(o.score)||o.score<0||o.score>100))throw Error();const official=structuredClone(defaults.weights),effective=structuredClone(official);if(user_weights!==null){if(!object(user_weights))throw Error();for(const[axis,w]of Object.entries(user_weights)){if(!Object.hasOwn(effective,axis)||!object(w))throw Error();for(const[f,v]of Object.entries(w)){if(!Object.hasOwn(effective[axis],f)||!finite(v)||v<0||v>100)throw Error();effective[axis][f]=v;}}}const axes={};for(const [axis,ws]of Object.entries(effective)){if(Math.abs(Object.values(ws).reduce((a,b)=>a+b,0)-100)>defaults.sum_tolerance)throw Error();let used=0,acc=0,blocked=false,missingAny=false;const missingIds=[],notApplicable=[];for(const[f,w]of Object.entries(ws)){if(profile_kind==='FINANCIAL'&&f==='roic_wacc'){notApplicable.push(f);continue;}const o=observations[f],available=o&&o.score!==null&&!['MISSING_DATA','BLOCKED_DEPENDENCY','PIT_UNAVAILABLE','NOT_APPLICABLE'].includes(o.quality);if(!available)missingIds.push(f);if(!o){missingAny=true;continue;}if(o.quality==='BLOCKED_DEPENDENCY'){blocked=true;continue;}if(!available){missingAny=true;continue;}acc+=(w/100)*o.score;used+=w/100;}axes[axis]={score:blocked||used===0?null:acc,coverage:blocked||used===0?'BLOCKED':missingAny||used<1-1e-12?'PARTIAL':'READY',missing_factor_ids:missingIds,not_applicable_ids:notApplicable,missing_factor_count:missingIds.length};}return{axes,qg_preview_total:axes.Q.score===null||axes.G.score===null?null:roundEven((axes.Q.score+axes.G.score)/2,4),official_weights:official,effective_weights:effective,role:'PREVIEW',parent_mix_note:'UNDEFINED_PARENT_WEIGHTS'};}catch(_){return{state:'INVALID_INPUT'};}}
/* #135 qgv.type_config + qgv.company_types port. PREVIEW only; the official v1 file is not loaded here. */
const PILLARS=['Q','G','V'],ID=/^[a-z][a-z0-9_]{0,63}$/,METRIC=/^[a-z][a-z0-9_]{0,95}$/,REASON=/^[A-Z][A-Z0-9_]{0,95}$/,compiled=new WeakMap();
function allFinite(v,depth=0){if(depth>64)return false;if(typeof v==='number')return Number.isFinite(v);if(Array.isArray(v))return v.every(x=>allFinite(x,depth+1));if(object(v))return Object.values(v).every(x=>allFinite(x,depth+1));return v===null||['string','boolean'].includes(typeof v);}
function validateTypeConfig(config){const errors=[],err=c=>{if(!errors.includes(c))errors.push(c);};
 const weights=v=>{if(!object(v)||Object.keys(v).length!==3||!PILLARS.every(p=>Object.hasOwn(v,p))||Object.values(v).some(x=>!finite(x)||x<0||x>100)){err('WEIGHT_INVALID');return;}if(Math.abs(PILLARS.reduce((a,p)=>a+v[p],0)-100)>1e-9)err('WEIGHT_SUM');};
 const rule=(v,depth=0)=>{if(!object(v)||depth>8){err('RULE_INVALID');return;}const kind=v.kind;if(!['ramp','gated_ramp','rank','unresolved'].includes(kind)){err('RULE_KIND');return;}
  if(kind!=='unresolved'&&(typeof v.metric!=='string'||!METRIC.test(v.metric)))err('METRIC_INVALID');
  if((kind==='ramp'||kind==='gated_ramp')&&(!finite(v.lower)||!finite(v.upper)||v.lower>=v.upper))err('RAMP_BOUNDS');
  if(kind==='gated_ramp'&&(typeof v.gate_metric!=='string'||!METRIC.test(v.gate_metric)))err('METRIC_INVALID');
  if(kind==='rank'&&(!Number.isInteger(v.max_rank)||v.max_rank<1))err('RANK_BOUND');
  if(kind==='unresolved'){const r=v.reasons;if(!Array.isArray(r)||!r.length||r.some(x=>typeof x!=='string'||!REASON.test(x)))err('UNRESOLVED_REASONS');if(Object.hasOwn(v,'components')){if(!Array.isArray(v.components))err('RULE_INVALID');else v.components.forEach(c=>rule(c,depth+1));}}};
 if(!object(config))return['CONFIG_INVALID'];
 if(config.schema_version!==1)err('SCHEMA_VERSION');if(typeof config.config_version!=='string'||!config.config_version)err('CONFIG_VERSION');
 let types=config.types;const ids=[];if(!Array.isArray(types)||types.length>128){err('TYPES_INVALID');types=[];}
 for(const item of types){if(!object(item)){err('TYPE_INVALID');continue;}const id=item.id;
  if(typeof id!=='string'||!ID.test(id))err('TYPE_ID_INVALID');else if(ids.includes(id))err('TYPE_ID_DUPLICATE');else ids.push(id);
  if(typeof item.name!=='string'||!item.name.trim()||item.name.length>128)err('TYPE_NAME_INVALID');
  if(typeof item.affects_qgv!=='boolean')err('TYPE_ROLE_INVALID');
  if((item.type_role==='EXPOSURE_ONLY'||id==='theme')&&item.affects_qgv)err('THEME_QGV_FORBIDDEN');
  if(item.affects_qgv)weights(item.weights);else if(Object.hasOwn(item,'weights'))err('DISPLAY_TYPE_WEIGHTS_FORBIDDEN');rule(item.rule);}
 const fb=config.fallback;if(!object(fb))err('FALLBACK_INVALID');else{if(typeof fb.id!=='string'||!ID.test(fb.id)||typeof fb.name!=='string'||!fb.name.trim())err('FALLBACK_INVALID');if(ids.includes(fb.id))err('TYPE_ID_DUPLICATE');weights(fb.weights);}
 const mix=config.mixing;if(!object(mix))err('MIXING_INVALID');else{const t=mix.minimum_membership,n=mix.maximum_types,lo=mix.pillar_min,hi=mix.pillar_max;
  if(!finite(t)||!(t>0&&t<=1)||!Number.isInteger(n)||n<1||n>128)err('MIXING_INVALID');if(!finite(lo)||!finite(hi)||!(0<=lo&&lo<hi&&hi<=100))err('MIXING_INVALID');
  if(mix.tie_break!=='CONFIG_ORDER'||mix.clamp_then_normalize!==true)err('MIXING_INVALID');
  if(!Array.isArray(mix.exclusive_pairs))err('MIXING_INVALID');else for(const pair of mix.exclusive_pairs)if(!Array.isArray(pair)||pair.length!==2||pair[0]===pair[1]||pair.some(p=>!ids.includes(p)))err('EXCLUSIVE_PAIR_INVALID');}
 const basis=config.value_basis;if(!object(basis)||!Object.hasOwn(basis,'cyclical_type')||basis.cyclical_type!==null&&!ids.includes(basis.cyclical_type))err('VALUE_BASIS_INVALID');
 else if(basis.cyclical_type!==null&&(!Number.isInteger(basis.normalized_years)||basis.normalized_years<1||typeof basis.required_metric!=='string'))err('VALUE_BASIS_INVALID');
 if(!object(config.themes)||config.themes.role!=='EXPOSURE_ONLY')err('THEME_ROLE_INVALID');return errors;}
function compileCustomTypeConfig(config){const out=compiled.get(config);if(out)config=JSON.parse(out.payload);const errors=validateTypeConfig(config);if(errors.length)return{state:'INVALID_INPUT',reason_codes:errors};
 if(!allFinite(config))return{state:'INVALID_INPUT',reason_codes:['CONFIG_INVALID']};let copy;try{copy=JSON.parse(JSON.stringify(config));}catch(_){return{state:'INVALID_INPUT',reason_codes:['CONFIG_INVALID']};}
 copy.status='CUSTOM_PREVIEW';const handle=Object.freeze({state:'COMPILED',official:false,config_version:copy.config_version});compiled.set(handle,{payload:JSON.stringify(copy),official:false});return handle;}
function membership(rule,metrics){const kind=rule.kind,evidence={},output=(value,reasons=[],components)=>({membership:value,state:value===null?'NOT_AVAILABLE':'PROVISIONAL',reason_codes:[...reasons],evidence,...(components!==undefined?{components}:{})});
 if(kind==='unresolved')return output(null,rule.reasons,(rule.components||[]).map(r=>membership(r,metrics)));
 const value=Object.hasOwn(metrics,rule.metric)?metrics[rule.metric]:undefined;evidence[rule.metric]=finite(value)?value:null;
 if(kind==='gated_ramp'){const gate=Object.hasOwn(metrics,rule.gate_metric)?metrics[rule.gate_metric]:undefined;evidence[rule.gate_metric]=typeof gate==='boolean'?gate:null;if(gate===false)return output(0);if(gate!==true)return output(null,['GATE_NOT_AVAILABLE']);}
 if(!finite(value))return output(null,['METRIC_NOT_AVAILABLE']);
 if(kind==='rank')return Number.isInteger(value)&&value>=1?output(value<=rule.max_rank?1:0):output(null,['RANK_NOT_AVAILABLE']);
 return output(Math.min(1,Math.max(0,(value-rule.lower)/(rule.upper-rule.lower))));}
function companyTypes({metrics,original_qgv,config}={}){const invalid=code=>({state:'INVALID_INPUT',reason_codes:[code]}),handle=compiled.get(config);
 if(!handle||!object(metrics)||!object(original_qgv))return invalid('INVALID_INPUT');const cfg=JSON.parse(handle.payload),errors=validateTypeConfig(cfg);if(errors.length)return{state:'INVALID_INPUT',reason_codes:errors};
 metrics=structuredClone(metrics);const originals={};for(const p of PILLARS)originals[p]=Object.hasOwn(original_qgv,p)&&original_qgv[p]!==undefined?original_qgv[p]:null;
 if(Object.values(originals).some(v=>v!==null&&(!finite(v)||v<0||v>100)))return invalid('QGV_INVALID');
 const types=cfg.types,memberships={},order={};types.forEach((t,i)=>{memberships[t.id]=membership(t.rule,metrics);order[t.id]=i;});const mix=cfg.mixing,m=id=>memberships[id].membership;
 const recognized=types.filter(t=>t.affects_qgv&&m(t.id)!==null&&m(t.id)>=mix.minimum_membership).sort((a,b)=>m(b.id)-m(a.id)||order[a.id]-order[b.id]),dropped=new Set();
 for(const [a,b]of mix.exclusive_pairs){const present=recognized.filter(t=>(t.id===a||t.id===b)&&!dropped.has(t.id));if(present.length===2)dropped.add(present[1].id);}
 const selected=recognized.filter(t=>!dropped.has(t.id)).slice(0,mix.maximum_types),reasons=[];let weights={};
 if(!selected.length){for(const p of PILLARS)weights[p]=cfg.fallback.weights[p];reasons.push(types.filter(t=>t.affects_qgv).every(t=>m(t.id)===null)?'TYPE_UNCONFIRMED':'NO_RECOGNIZED_TYPE');}
 else{const mass=selected.reduce((a,t)=>a+m(t.id),0);for(const p of PILLARS)weights[p]=selected.reduce((a,t)=>a+t.weights[p]*m(t.id),0)/mass;}
 const clamped={};for(const p of PILLARS)clamped[p]=Math.min(mix.pillar_max,Math.max(mix.pillar_min,weights[p]));const total=PILLARS.reduce((a,p)=>a+clamped[p],0);if(!(total>0))return invalid('MIXING_INVALID');
 weights={};for(const p of PILLARS)weights[p]=100*clamped[p]/total;const adjusted={...originals};
 if(selected.some(t=>t.id===cfg.value_basis.cyclical_type)){const v=Object.hasOwn(metrics,cfg.value_basis.required_metric)?metrics[cfg.value_basis.required_metric]:undefined;if(!finite(v)||v<0||v>100){adjusted.V=null;reasons.push('NORMALIZED_EARNINGS_VALUE_REQUIRED');}else adjusted.V=v;}
 const missingPillars=PILLARS.filter(p=>adjusted[p]===null);
 return{role:handle.official?'OFFICIAL_PROVISIONAL':'PREVIEW',config_status:handle.official?'OFFICIAL_PROVISIONAL':'CUSTOM_PREVIEW',config_version:cfg.config_version,calibration:'V2_PENDING',memberships,selected_types:selected.map(t=>t.id),excluded_unavailable:types.filter(t=>m(t.id)===null).map(t=>t.id),fallback_type:selected.length?null:cfg.fallback.id,weights,original_qgv:originals,adjusted_qgv:adjusted,adjusted_score:missingPillars.length?null:PILLARS.reduce((a,p)=>a+adjusted[p]*weights[p]/100,0),missing_pillars:missingPillars,reason_codes:reasons};}
return Object.freeze({dcf,reverseDcf,vFactors,strategy,validateTypeConfig,compileCustomTypeConfig,companyTypes,roundEven});
});
