/* #106/#110 supplied-input M3 port. No provider, model, storage or public serializer. */
(function(root,factory){const api=factory();if(typeof module==='object'&&module.exports)module.exports=api;else root.PrivateSubset=api;})(typeof globalThis!=='undefined'?globalThis:this,function(){
 'use strict';
 const CODES=new Set(['UNIVERSE_SCHEMA_MISMATCH','MANIFEST_MISMATCH','SOURCE_TOO_LARGE','ROW_LIMIT_REACHED','IDENTITY_UNCONFIRMED','CURRENCY_SCOPE_NOT_SUPPORTED','MIXED_SYNTHETIC_INPUT','GOOGLE_MCAP_MISSING','GOOGLE_MCAP_INVALID','PRICE_NOT_AVAILABLE','INVALID_INPUT','INVALID_TIMESTAMP','INVALID_TIME_ORDER','AVAILABLE_AFTER_AS_OF','BASIS_UNCONFIRMED','CIK_MISMATCH','ACCESSION_UNCONFIRMED','SHARES_NOT_AVAILABLE','MULTI_CLASS_AMBIGUOUS','NONFINITE_MCAP','CONFIG_CONFIRMATION_REQUIRED','DUPLICATE_ISSUER','VALIDATION_INCOMPLETE','SHARE_CLASS_BASIS']);
 const codes=x=>Array.isArray(x)&&x.every(v=>typeof v==='string'&&CODES.has(v));
 const text=x=>typeof x==='string'&&Boolean(x.trim()),hash=x=>typeof x==='string'&&/^[a-f0-9]{64}$/.test(x),positive=x=>typeof x==='number'&&Number.isFinite(x)&&x>0&&(!Number.isInteger(x)||Number.isSafeInteger(x));
 const day=x=>typeof x==='string'&&/^\d{4}-\d{2}-\d{2}$/.test(x)&&Number.isFinite(Date.parse(x+'T00:00:00Z'))&&new Date(x+'T00:00:00Z').toISOString().slice(0,10)===x;
 const time=x=>typeof x==='string'&&/^\d{4}-\d{2}-\d{2}T\d{2}:\d{2}:\d{2}(?:\.\d+)?(?:Z|[+-]\d{2}:\d{2})$/.test(x)&&day(x.slice(0,10))&&Number(x.slice(11,13))<24&&Number(x.slice(14,16))<60&&Number(x.slice(17,19))<60&&Number.isFinite(Date.parse(x));
 const stamp=x=>Date.parse(x),utcDay=x=>new Date(stamp(x)).toISOString().slice(0,10);
 const freeze=x=>Object.freeze(x),same=(a,b)=>JSON.stringify(a)===JSON.stringify(b);
 function bytes(x){return x instanceof Uint8Array?x:typeof x==='string'?new TextEncoder().encode(x):null;}
 async function digest(x){return Array.from(new Uint8Array(await globalThis.crypto.subtle.digest('SHA-256',bytes(x))),x=>x.toString(16).padStart(2,'0')).join('');}
 function canonical(x){if(Array.isArray(x))return '['+x.map(canonical).join(',')+']';if(x&&typeof x==='object')return '{'+Object.keys(x).sort().map(k=>JSON.stringify(k)+':'+canonical(x[k])).join(',')+'}';if(typeof x==='number'&&!Number.isFinite(x))return Number.isNaN(x)?'NaN':x>0?'Infinity':'-Infinity';return JSON.stringify(x);}
 function canonicalValues(x){return canonical(x).replace(/[\u007f-\uffff]/g,c=>'\\u'+c.charCodeAt(0).toString(16).padStart(4,'0'));}
 function identityError(seed,at,synthetic){
  if(!seed||['listing_id','company_id','issuer_id','security_id','symbol','mic','currency','timezone','provider_symbol','identity_evidence_ref'].some(k=>!text(seed[k]))||!hash(seed.identity_sha256)||!/^[a-z0-9_-]+$/.test(seed.company_id)||typeof seed.cik!=='string'||!/^\d{10}$/.test(seed.cik)||seed.cik==='0000000000'||!day(seed.valid_from)||(seed.valid_to!==null&&(!day(seed.valid_to)||seed.valid_to<=seed.valid_from))||seed.valid_from>utcDay(at)||(seed.valid_to!==null&&utcDay(at)>=seed.valid_to))return 'IDENTITY_UNCONFIRMED';
  if(typeof seed.synthetic!=='boolean'||seed.synthetic!==synthetic)return 'MIXED_SYNTHETIC_INPUT';return seed.currency==='USD'?null:'CURRENCY_SCOPE_NOT_SUPPORTED';
 }
 function receiptValid(r){return r&&r.source==='GOOGLEFINANCE_PRIVATE_UNIVERSE'&&time(r.acquired_at)&&hash(r.content_sha256)&&typeof r.job_id==='string'&&/^[A-Za-z0-9_-]{1,128}$/.test(r.job_id)&&Number.isSafeInteger(r.session_epoch)&&r.session_epoch>=0&&typeof r.synthetic==='boolean';}
 function number(x){if(typeof x==='string'&&/^\+?[0-9]+(?:\.[0-9]+)?$/.test(x))x=Number(x);return positive(x)?x:null;}
 async function parseUniverseValues(values,receipt,identityLookup={}){
  const fail=code=>freeze({state:'NOT_AVAILABLE',rows:freeze([]),row_count:0,reason_codes:freeze([code]),row_limit_reached:false,receipt,synthetic:true});
  if(!receipt||receipt.source!=='GOOGLEFINANCE_PRIVATE_UNIVERSE'||!hash(receipt.content_sha256)||!text(receipt.job_id)||!Number.isSafeInteger(receipt.session_epoch)||receipt.session_epoch<0||typeof receipt.synthetic!=='boolean'||!Array.isArray(values)||!identityLookup||typeof identityLookup!=='object')return fail('UNIVERSE_SCHEMA_MISMATCH');
  if(!time(receipt.acquired_at))return fail('INVALID_TIMESTAMP');values=structuredClone(values);receipt=freeze({...receipt});identityLookup=Object.fromEntries(Object.entries(identityLookup).map(([k,v])=>[k,v?freeze({...v}):v]));
  let encoded;try{encoded=canonicalValues(values);}catch(_){return fail('UNIVERSE_SCHEMA_MISMATCH');}if(bytes(encoded).length>1048576)return fail('SOURCE_TOO_LARGE');if(await digest(encoded)!==receipt.content_sha256)return fail('MANIFEST_MISMATCH');
  const header=values[0],start=Array.isArray(header)&&header.length===3&&header.every(x=>typeof x==='string')&&same(header.map(x=>x.toLowerCase()),['code','marketcap','price'])?1:0;
  let end=values.length;while(end>start&&Array.isArray(values[end-1])&&values[end-1].every(x=>x===null||x===''))end--;const limited=end-start>=1024,unique=new Map();
  for(let i=start;i<Math.min(end,start+1024);i++){
   const raw=values[i];let row;if(!Array.isArray(raw)||raw.length>3)row={row_index:i,code:null,listing:null,google_mcap:null,sheet_price:null,reason_codes:['UNIVERSE_SCHEMA_MISMATCH'],receipt};
   else{const code=text(raw[0])?raw[0]:null,seed=code!==null&&Object.hasOwn(identityLookup,code)?identityLookup[code]:null;let error=identityError(seed,receipt.acquired_at,receipt.synthetic);if(!error&&code.includes(':')&&!new Set(['NASDAQ:XNAS','NYSE:XNYS']).has(code.split(':')[0]+':'+seed.mic))error='IDENTITY_UNCONFIRMED';const google=number(raw[1]),price=number(raw[2]),reasons=[];if(error)reasons.push(error);else{if(google===null)reasons.push(raw[1]===undefined||raw[1]===null||raw[1]===''?'GOOGLE_MCAP_MISSING':'GOOGLE_MCAP_INVALID');if(price===null)reasons.push('PRICE_NOT_AVAILABLE');}row={row_index:i,code,listing:error?null:seed,google_mcap:google,sheet_price:price,reason_codes:reasons,receipt};}
   const key=row.listing?'listing:'+row.listing.listing_id:row.code?'code:'+row.code:'index:'+i,old=unique.get(key);if(!old)unique.set(key,row);else if(!same([old.listing,old.google_mcap,old.sheet_price,old.reason_codes],[row.listing,row.google_mcap,row.sheet_price,row.reason_codes]))unique.set(key,{...old,google_mcap:null,sheet_price:null,reason_codes:['INVALID_INPUT']});
  }
  const rows=[...unique.values()].map(r=>freeze({...r,reason_codes:freeze(r.reason_codes)}));return freeze({state:rows.length?'INPUT_RESEARCH':'NOT_AVAILABLE',receipt,rows:freeze(rows),row_count:rows.length,reason_codes:freeze(limited?['ROW_LIMIT_REACHED']:[]),row_limit_reached:limited,synthetic:receipt.synthetic});
 }
 function rowValid(row){return row&&Number.isSafeInteger(row.row_index)&&row.row_index>=0&&(row.code===null||text(row.code))&&receiptValid(row.receipt)&&(row.listing===null||identityError(row.listing,row.receipt.acquired_at,row.receipt.synthetic)===null)&&codes(row.reason_codes)&&(row.google_mcap===null||positive(row.google_mcap))&&(row.sheet_price===null||positive(row.sheet_price));}
 function basisError(seed,basis,asof,synthetic){
  if(basis)basis={...basis,share_class_basis:basis.share_class_basis??'UNKNOWN'};
  if(!basis||['listing_id','company_id','security_id'].some(k=>basis[k]!==seed[k])||!['SINGLE_CLASS_CONFIRMED','CA_UNIT_APPROVED','UNKNOWN'].includes(basis.basis_status)||!['ALIGNED','DIFFERENT','UNKNOWN'].includes(basis.share_class_basis)||!text(basis.source_evidence_ref)||!hash(basis.source_sha256)||basis.share_unit!=='shares'||basis.price_basis!=='GOOGLEFINANCE_CURRENT'||basis.currency!==seed.currency)return 'BASIS_UNCONFIRMED';
  if(!time(basis.available_at))return 'INVALID_TIMESTAMP';if(stamp(basis.available_at)>stamp(asof))return 'AVAILABLE_AFTER_AS_OF';if(typeof basis.synthetic!=='boolean'||basis.synthetic!==synthetic)return 'MIXED_SYNTHETIC_INPUT';if(basis.share_class_basis==='DIFFERENT')return 'SHARE_CLASS_BASIS';return basis.basis_status==='UNKNOWN'?'BASIS_UNCONFIRMED':null;
 }
 const cik=x=>(typeof x==='number'&&Number.isSafeInteger(x)&&x>0||typeof x==='string'&&/^\d{1,10}$/.test(x))?String(x).padStart(10,'0'):null;
 async function prepareSecShares(seed,receipt,basis,asof){
  const base={listing_id:seed?.listing_id??null,company_id:seed?.company_id??null,security_id:seed?.security_id??null,synthetic:typeof receipt?.synthetic==='boolean'?receipt.synthetic:true,historical_first_publication:false};
  const fail=code=>freeze({...base,state:'NOT_AVAILABLE',shares:null,shares_available_at:null,measurement_date:null,accn:null,concept:null,basis_sha256:code==='SHARE_CLASS_BASIS'?basis.source_sha256:null,facts_sha256:code==='SHARE_CLASS_BASIS'?receipt.facts_sha256:null,submissions_sha256:code==='SHARE_CLASS_BASIS'?receipt.submissions_sha256:null,reason_codes:freeze([code])});
  if(!receipt)return fail('INVALID_INPUT');receipt={...receipt,companyfacts_body:bytes(receipt.companyfacts_body)?.slice()??null,submissions_body:bytes(receipt.submissions_body)?.slice()??null};if(typeof receipt.synthetic!=='boolean')return fail('MIXED_SYNTHETIC_INPUT');if(!time(asof)||!time(receipt.acquired_at))return fail('INVALID_TIMESTAMP');let error=identityError(seed,receipt.acquired_at,receipt.synthetic);if(error)return fail(error);if(receipt.cik!==seed.cik)return fail('CIK_MISMATCH');if(stamp(receipt.acquired_at)>stamp(asof))return fail('AVAILABLE_AFTER_AS_OF');
  for(const [body,sha]of [[receipt.companyfacts_body,receipt.facts_sha256],[receipt.submissions_body,receipt.submissions_sha256]]){const b=bytes(body);if(!b||!hash(sha))return fail('INVALID_INPUT');if(b.length>8388608)return fail('SOURCE_TOO_LARGE');if(await digest(b)!==sha)return fail('MANIFEST_MISMATCH');}
  let facts,sub;try{const dec=new TextDecoder('utf-8',{fatal:true});facts=JSON.parse(dec.decode(bytes(receipt.companyfacts_body)));sub=JSON.parse(dec.decode(bytes(receipt.submissions_body)));}catch(_){return fail('INVALID_INPUT');}if(cik(facts?.cik)!==seed.cik||cik(sub?.cik)!==seed.cik)return fail('CIK_MISMATCH');error=basisError(seed,basis,asof,receipt.synthetic);if(error)return fail(error);
  const rec=sub.filings?.recent,keys=['accessionNumber','form','filingDate','acceptanceDateTime'];if(!rec||keys.some(k=>!Array.isArray(rec[k]))||new Set(keys.map(k=>rec[k].length)).size!==1)return fail('ACCESSION_UNCONFIRMED');
  const index=new Map();for(let i=0;i<rec.form.length;i++){const accn=rec.accessionNumber[i],form=rec.form[i],filed=rec.filingDate[i],accepted=rec.acceptanceDateTime[i];if(typeof accn!=='string'||!/^\d{10}-\d{2}-\d{6}$/.test(accn)||!['10-K','10-K/A','20-F','20-F/A','40-F','10-Q','10-Q/A','6-K'].includes(form)||!day(filed))continue;let reason=!accepted?'ACCESSION_UNCONFIRMED':!time(accepted)?'INVALID_TIMESTAMP':stamp(accepted)>stamp(receipt.acquired_at)||filed>utcDay(receipt.acquired_at)||utcDay(accepted)<filed?'INVALID_TIME_ORDER':null;const entry={accepted,reason,form,filed};if(index.has(accn)&&!same(index.get(accn),entry))reason='ACCESSION_UNCONFIRMED';index.set(accn,{...entry,reason});}
  let last='SHARES_NOT_AVAILABLE';for(const [taxonomy,concept]of [['dei','EntityCommonStockSharesOutstanding'],['us-gaap','CommonStockSharesOutstanding']]){
   const rows=facts.facts?.[taxonomy]?.[concept]?.units?.shares;if(!Array.isArray(rows))continue;const eligible=[];
   for(const row of rows){if(!row||!positive(row.val)||!day(row.end))continue;const filing=index.get(row.accn);if(!filing){last='ACCESSION_UNCONFIRMED';continue;}if(filing.reason){last=filing.reason;continue;}if(row.form!==filing.form||row.filed!==filing.filed||row.end>filing.filed||row.end>utcDay(receipt.acquired_at)){last='SHARES_NOT_AVAILABLE';continue;}eligible.push({...row,accepted:filing.accepted});}
   if(eligible.length){eligible.sort((a,b)=>stamp(b.accepted)-stamp(a.accepted)||b.filed.localeCompare(a.filed)||b.accn.localeCompare(a.accn)||b.end.localeCompare(a.end));const first=eligible[0],values=new Set(eligible.filter(r=>stamp(r.accepted)===stamp(first.accepted)&&r.filed===first.filed&&r.accn===first.accn&&r.end===first.end).map(r=>r.val));if(values.size!==1)return fail('MULTI_CLASS_AMBIGUOUS');return freeze({...base,state:'INPUT_RESEARCH',shares:first.val,shares_available_at:receipt.acquired_at,measurement_date:first.end,accn:first.accn,concept:taxonomy+':'+concept,basis_sha256:basis.source_sha256,facts_sha256:receipt.facts_sha256,submissions_sha256:receipt.submissions_sha256,reason_codes:freeze([])});}
  }return fail(last);
 }
 function prepareUniversePrice(row,basis,asof){
  const seed=row?.listing,r=row?.receipt,base={listing_id:seed?.listing_id??null,company_id:seed?.company_id??null,security_id:seed?.security_id??null,as_of:asof,content_sha256:r?.content_sha256??null,row_index:row?.row_index??null,basis_sha256:basis?.source_sha256??null,synthetic:r?.synthetic??true,price_kind:'GOOGLEFINANCE_CURRENT',trade_time:null,exact_eod:false};
  const result=code=>freeze({...base,state:code?'NOT_AVAILABLE':'INPUT_RESEARCH',price:code?null:row.sheet_price,available_at:code?null:r.acquired_at,observed_at:code?null:r.acquired_at,reason_codes:freeze(code?[code]:[])});
  if(!seed||!receiptValid(r))return result('IDENTITY_UNCONFIRMED');if(!rowValid(row))return result('INVALID_INPUT');if(!time(asof))return result('INVALID_TIMESTAMP');if(stamp(r.acquired_at)>stamp(asof))return result('AVAILABLE_AFTER_AS_OF');const error=basisError(seed,basis,asof,r.synthetic);if(error)return result(error);if(row.reason_codes.includes('INVALID_INPUT'))return result('INVALID_INPUT');return result(positive(row.sheet_price)?null:'PRICE_NOT_AVAILABLE');
 }
 function fraction(x){let [mantissa,exponent='0']=String(x).split('e'),[whole,decimals='']=mantissa.split('.');const power=Number(exponent)-decimals.length;let n=BigInt(whole+decimals),d=1n;if(power>=0)n*=10n**BigInt(power);else d=10n**BigInt(-power);return {n,d};}
 function relative(google,cap,tolerance){const a=fraction(google),b=fraction(cap),t=fraction(tolerance);let n=a.n*b.d-b.n*a.d;if(n<0n)n=-n;const d=a.d*b.n,ns=n.toString(),ds=d.toString(),value=n===0n?0:Number(ns.slice(0,16))/Number(ds.slice(0,16))*10**((ns.length-Math.min(16,ns.length))-(ds.length-Math.min(16,ds.length)));return {value,mismatch:n*t.d>=d*t.n};}
 function compareUniverseMarketCap(row,shares,price,config={relative_tolerance:.1,confirmed:true}){
  const seed=row?.listing,r=row?.receipt,base={row_index:row?.row_index??-1,listing:seed??null,google_mcap:row?.google_mcap??null,content_sha256:r?.content_sha256??'',synthetic:r?.synthetic??true};
  const result=(code=null,cap=null,diff=null,quality='UNCONFIRMED')=>freeze({...base,state:code?'NOT_AVAILABLE':'VERIFIED',recomputed_cap:cap,effective_cap:cap,relative_difference:diff,quality:code==='SHARE_CLASS_BASIS'?'SHARE_CLASS_BASIS':quality,quality_label:code==='SHARE_CLASS_BASIS'?'SHARE_CLASS_BASIS':quality==='MISMATCH'?'검증 불일치':'',reason_codes:freeze(code?[code]:[]),shares_input:code?null:shares,price_input:code?null:price});
  if(!seed||!receiptValid(r)||!shares||!price||['listing_id','company_id','security_id'].some(k=>shares[k]!==seed[k]||price[k]!==seed[k]))return result('IDENTITY_UNCONFIRMED');
  if(!rowValid(row)||!codes(shares.reason_codes)||!codes(price.reason_codes)||shares.historical_first_publication!==false)return result('INVALID_INPUT');if(!time(price.as_of))return result('INVALID_TIMESTAMP');
  if(shares.state!=='INPUT_RESEARCH'){if(shares.reason_codes.includes('SHARE_CLASS_BASIS')&&(!hash(shares.basis_sha256)||shares.basis_sha256!==price.basis_sha256||!hash(shares.facts_sha256)||!hash(shares.submissions_sha256)))return result('BASIS_UNCONFIRMED');return result(shares.reason_codes[0]||'SHARES_NOT_AVAILABLE');}
  if(!time(shares.shares_available_at)||!time(r.acquired_at))return result('INVALID_TIMESTAMP');if(stamp(shares.shares_available_at)>stamp(price.as_of)||stamp(r.acquired_at)>stamp(price.as_of))return result('AVAILABLE_AFTER_AS_OF');
  if(!positive(shares.shares)||!day(shares.measurement_date)||shares.measurement_date>utcDay(shares.shares_available_at)||!text(shares.accn)||!['dei:EntityCommonStockSharesOutstanding','us-gaap:CommonStockSharesOutstanding'].includes(shares.concept)||!hash(shares.facts_sha256)||!hash(shares.submissions_sha256))return result('SHARES_NOT_AVAILABLE');
  if(!hash(shares.basis_sha256)||shares.basis_sha256!==price.basis_sha256)return result('BASIS_UNCONFIRMED');if(price.state!=='INPUT_RESEARCH')return result(price.reason_codes[0]||'PRICE_NOT_AVAILABLE');
  if(price.content_sha256!==r.content_sha256||price.row_index!==row.row_index||price.price!==row.sheet_price||!positive(price.price)||price.price_kind!=='GOOGLEFINANCE_CURRENT'||price.exact_eod!==false||price.trade_time!==null)return result('MANIFEST_MISMATCH');
  if(!time(price.available_at)||!time(price.observed_at)||stamp(price.available_at)!==stamp(r.acquired_at)||stamp(price.observed_at)!==stamp(r.acquired_at))return result('INVALID_TIME_ORDER');if(seed.currency!=='USD')return result('CURRENCY_SCOPE_NOT_SUPPORTED');if([shares.synthetic,price.synthetic,r.synthetic].some(x=>typeof x!=='boolean')||new Set([shares.synthetic,price.synthetic,r.synthetic]).size!==1)return result('MIXED_SYNTHETIC_INPUT');if(config.confirmed!==true)return result('CONFIG_CONFIRMATION_REQUIRED');if(!positive(config.relative_tolerance))return result('INVALID_INPUT');
  const cap=shares.shares*price.price;if(!positive(cap))return result('NONFINITE_MCAP');if(row.google_mcap===null)return result(null,cap,null,row.reason_codes.includes('GOOGLE_MCAP_MISSING')?'GOOGLE_MCAP_MISSING':'GOOGLE_MCAP_INVALID');if(!positive(row.google_mcap))return result('INVALID_INPUT');const diff=relative(row.google_mcap,cap,config.relative_tolerance);if(!Number.isFinite(diff.value))return result('NONFINITE_MCAP');return result(null,cap,diff.value,diff.mismatch?'MISMATCH':'WITHIN_TOLERANCE');
 }
 function selectVerifiedUniverseTopN(checks,parsed,{n=20,confirmed=true}={}){
  const fail=code=>freeze({state:'NOT_AVAILABLE',status:'UNCONFIRMED',selection_status:'UNCONFIRMED',source:'PRIVATE_UNIVERSE_VERIFIED_TOP_N',scope:'VERIFIED_UNIVERSE_ROWS',official:false,candidate_pool_complete:false,full_configured_rank_status:'UNKNOWN',selected:freeze([]),missing:freeze([]),reason_codes:freeze([code]),requested_n:n,selected_count:0});
  if(!parsed||parsed.state!=='INPUT_RESEARCH'||!receiptValid(parsed.receipt)||!Array.isArray(parsed.rows)||parsed.row_count!==parsed.rows.length||!parsed.rows.length||parsed.rows.length>1024||!Array.isArray(checks)||!codes(parsed.reason_codes)||typeof parsed.row_limit_reached!=='boolean'||typeof parsed.synthetic!=='boolean'||parsed.synthetic!==parsed.receipt.synthetic||parsed.rows.some(r=>!rowValid(r))||checks.some(c=>!c||!Number.isSafeInteger(c.row_index)||!codes(c.reason_codes))||new Set(parsed.rows.map(r=>r.row_index)).size!==parsed.row_count)return fail('INVALID_INPUT');if(confirmed!==true)return fail('CONFIG_CONFIRMATION_REQUIRED');if(!Number.isSafeInteger(n)||n<1||n>parsed.row_count)return fail('INVALID_INPUT');
  const indexed=new Map(),issuers=new Map();for(const row of parsed.rows){if(row.receipt.content_sha256!==parsed.receipt.content_sha256||row.receipt.job_id!==parsed.receipt.job_id||row.receipt.session_epoch!==parsed.receipt.session_epoch||row.receipt.synthetic!==parsed.synthetic||stamp(row.receipt.acquired_at)!==stamp(parsed.receipt.acquired_at))return fail('MANIFEST_MISMATCH');if(row.listing)issuers.set(row.listing.issuer_id,(issuers.get(row.listing.issuer_id)||0)+1);}
  for(const c of checks){const row=parsed.rows.find(r=>r.row_index===c.row_index);if(!row||indexed.has(c.row_index)||c.content_sha256!==parsed.receipt.content_sha256||!same(c.listing,row.listing)||c.google_mcap!==row.google_mcap)return fail('MANIFEST_MISMATCH');if(c.synthetic!==parsed.synthetic)return fail('MIXED_SYNTHETIC_INPUT');if(c.reason_codes.includes('CONFIG_CONFIRMATION_REQUIRED'))return fail('CONFIG_CONFIRMATION_REQUIRED');if(!['VERIFIED','NOT_AVAILABLE'].includes(c.state)||(c.state==='VERIFIED'&&(!positive(c.effective_cap)||c.effective_cap!==c.recomputed_cap||!c.listing||c.reason_codes.length||!['WITHIN_TOLERANCE','MISMATCH','GOOGLE_MCAP_MISSING','GOOGLE_MCAP_INVALID'].includes(c.quality))))return fail('INVALID_INPUT');indexed.set(c.row_index,c);}
  const verified=[],missing=[],reasons=[...parsed.reason_codes];for(const row of parsed.rows){const c=indexed.get(row.row_index),codes=row.listing&&issuers.get(row.listing.issuer_id)>1?['DUPLICATE_ISSUER']:!c||c.state!=='VERIFIED'?c?.reason_codes?.length?c.reason_codes:row.reason_codes.length?row.reason_codes:['VALIDATION_INCOMPLETE']:null;if(codes){missing.push(freeze({row_index:row.row_index,reason_codes:freeze(codes)}));reasons.push(...codes);}else verified.push(c);}
  verified.sort((a,b)=>b.effective_cap-a.effective_cap||(a.listing.company_id<b.listing.company_id?-1:a.listing.company_id>b.listing.company_id?1:0));const selected=verified.slice(0,n),incomplete=missing.length>0||parsed.row_limit_reached||selected.length<n;if(incomplete)reasons.push('VALIDATION_INCOMPLETE');return freeze({state:selected.length?'PERSONAL_REFERENCE':'NOT_AVAILABLE',status:incomplete?'PARTIAL':'COMPLETE',selection_status:incomplete?'PARTIAL':'COMPLETE',content_sha256:parsed.receipt.content_sha256,selected_n:selected.length,verified_count:verified.length,missing_count:missing.length,selected_listing_ids:freeze(selected.map(c=>c.listing.listing_id)),synthetic:parsed.synthetic,source:'PRIVATE_UNIVERSE_VERIFIED_TOP_N',scope:'VERIFIED_UNIVERSE_ROWS',official:false,candidate_pool_complete:false,full_configured_rank_status:'UNKNOWN',selected:freeze(selected),missing:freeze(missing),reason_codes:freeze([...new Set(reasons)]),requested_n:n,selected_count:selected.length,verified_row_count:verified.length,row_count:parsed.row_count});
 }
 return freeze({digest,canonicalValues,parseUniverseValues,prepareSecShares,prepareUniversePrice,compareUniverseMarketCap,selectVerifiedUniverseTopN});
});
