/* Canonical price-free projection reader. Values are display evidence, never ranks. */
(function(root,factory){const api=factory();if(typeof module==='object'&&module.exports)module.exports=api;else root.PublicScreens=api;})(typeof globalThis==='object'?globalThis:this,function(){
'use strict';
const FILES={'macro-screen.json':'MACRO','sec-13f-changes.json':'SEC_13F','sec-filing-windows.json':'SEC_FILING_WINDOWS','sec-qg-factors.json':'SEC_QG_FACTORS','company-types-pricefree.json':'COMPANY_TYPES_PRICEFREE'};
const IDS=['asml','lrcx','klac','tokyo_electron','hanmi','nvda','amd','avgo','qcom','intc','msft','googl','amzn','rtx','stry','etn','hubb','gev','rok'];
const FACTORS=['competitive_advantage','eps_fcf_per_share_growth','excess_growth_vs_industry','fcf_quality','financial_health','growth_durability','growth_efficiency','management_quality','margin_quality','market_position','next_3_5y_growth','revenue_growth','roic_wacc'];
const AXES=['Growth','Inflation','Liquidity','Monetary Policy','Credit','Labor','Fiscal','FX'],DIMENSIONS=['Level','Direction','Momentum','Surprise','Stress','Confidence'];
const TYPES=['growth','quality','cyclical','defensive'],STATES=['LIVE','STALE','NOT_AVAILABLE'];
const REASONS=['NO_ELIGIBLE_INPUT','SOURCE_NOT_AVAILABLE','SYNTHETIC_INPUT_NOT_PUBLIC','SOURCE_AFTER_AS_OF','STALE_INPUT','UPSTREAM_NOT_AVAILABLE','TYPE_ENGINE_PENDING_MERGE','CRITERIA_UNDEFINED','PUBLIC_FX_EXCLUDED','UNAPPROVED_ENGINE_INPUT_MAPPING'];
const LEVEL={Growth:['BEA:NIPA:T10106:1:Q'],Inflation:['BLS:CUSR0000SA0','BLS:CUUR0000SA0'],Labor:['BLS:CES0000000001','BLS:LNS14000000'],'Monetary Policy':['TREASURY:daily_treasury_yield_curve:BC_10YEAR']};
const REGISTRY={'BLS:CUSR0000SA0':['BLS','Inflation'],'BLS:CUUR0000SA0':['BLS','Inflation'],'BLS:CES0000000001':['BLS','Labor'],'BLS:LNS14000000':['BLS','Labor'],'BEA:NIPA:T10106:1:Q':['BEA','Growth'],'BEA:NIPA:T10101:1:Q':['BEA','Growth'],'TREASURY:daily_treasury_yield_curve:BC_10YEAR':['TREASURY','Monetary Policy']};
const MAX=2*1024*1024,hash=v=>typeof v==='string'&&/^[0-9a-f]{64}$/.test(v),number=v=>typeof v==='number'&&Number.isFinite(v);
function need(v){if(!v)throw Error('PUBLIC_SCREEN_INVALID');}
function object(v){return v!==null&&typeof v==='object'&&!Array.isArray(v);}
function keys(v,ks){need(object(v)&&Object.keys(v).length===ks.length&&ks.every(k=>Object.hasOwn(v,k)));}
function clock(v){need(typeof v==='string'&&/^\d{4}-\d{2}-\d{2}T\d{2}:\d{2}:\d{2}(?:\.\d{1,6})?(?:Z|[+-]\d{2}:\d{2})$/.test(v));const n=Date.parse(v);need(Number.isFinite(n));return n;}
function day(v){need(typeof v==='string'&&/^\d{4}-\d{2}-\d{2}$/.test(v)&&new Date(v+'T00:00:00Z').toISOString().slice(0,10)===v);return v;}
function aggregate(states){return states.includes('LIVE')?'LIVE':states.includes('STALE')?'STALE':'NOT_AVAILABLE';}
function score(v,max=100){need(v===null||number(v)&&v>=0&&v<=max);}
function validate(name,p){
 need(Object.hasOwn(FILES,name)&&new TextEncoder().encode(JSON.stringify(p)).length<=MAX);
 keys(p,['schema_version','kind','as_of','state','sources','reason_codes','freshness_basis','stale_after_seconds','data']);
 need(p.schema_version===1&&p.kind===FILES[name]&&STATES.includes(p.state)&&p.freshness_basis==='SOURCE_ACQUISITION'&&number(p.stale_after_seconds)&&p.stale_after_seconds>0);
 const cut=clock(p.as_of),fresh=stamp=>cut-stamp>p.stale_after_seconds*1000?'STALE':'LIVE';
 need(Array.isArray(p.reason_codes)&&p.reason_codes.every(r=>REASONS.includes(r))&&Array.isArray(p.sources)&&p.sources.length<=10000);
 const agencies=name==='macro-screen.json'?['BLS','BEA','TREASURY','FED_H41','FED_H8','FED_H10','TREASURY_MTS']:name==='sec-13f-changes.json'?['SEC_13F']:['SEC_COMPANYFACTS','SEC_SUBMISSIONS'],sources=new Map(),states=[];
 for(const s of p.sources){keys(s,['agency','sha256','acquired_at']);need(agencies.includes(s.agency)&&hash(s.sha256));const stamp=clock(s.acquired_at),key=s.agency+':'+s.sha256;need(stamp<=cut&&(!sources.has(key)||sources.get(key)===stamp));sources.set(key,stamp);}
 function refs(row,map){need(object(row.source_hashes)&&Object.keys(row.source_hashes).every(k=>Object.hasOwn(map,k)));for(const [key,value]of Object.entries(row.source_hashes))need(hash(value)&&sources.has(map[key]+':'+value));if(row.state!=='NOT_AVAILABLE'){keys(row.source_hashes,Object.keys(map));const last=Object.keys(map).at(-1);need(row.state===fresh(sources.get(map[last]+':'+row.source_hashes[last])));}}
 const d=p.data;
 if(name==='sec-qg-factors.json'||name==='company-types-pricefree.json'||name==='sec-filing-windows.json'){
  keys(d,name==='sec-filing-windows.json'?['companies']:['companies','method_status','availability_basis']);keys(d.companies,IDS);
  if(name!=='sec-filing-windows.json')need(d.method_status==='PROVISIONAL_UNCALIBRATED'&&d.availability_basis==='OBSERVED_CAPTURE_ONLY');
  for(const r of Object.values(d.companies)){
   keys(r,name==='sec-qg-factors.json'?['state','factors','source_hashes']:name==='company-types-pricefree.json'?['state','memberships','config_version','source_hashes']:['state','role','confirmed_earnings_date','groups','source_hashes']);need(STATES.includes(r.state));states.push(r.state);refs(r,{companyfacts:'SEC_COMPANYFACTS',submissions:'SEC_SUBMISSIONS'});
   if(name==='sec-qg-factors.json'){keys(r.factors,FACTORS);for(const f of Object.values(r.factors)){keys(f,['score','state']);score(f.score);need(STATES.includes(f.state)&&(f.state==='NOT_AVAILABLE')===(f.score===null)&&['NOT_AVAILABLE',r.state].includes(f.state));}need(r.state===aggregate(Object.values(r.factors).map(f=>f.state)));}
   else if(name==='company-types-pricefree.json'){keys(r.memberships,TYPES);need([null,'type_config/1'].includes(r.config_version));Object.values(r.memberships).forEach(v=>score(v,1));need((r.state==='NOT_AVAILABLE')===Object.values(r.memberships).every(v=>v===null));}
   else{need(r.role==='ESTIMATED_PATTERN_NOT_CONFIRMED'&&r.confirmed_earnings_date===null&&Array.isArray(r.groups)&&(r.state==='NOT_AVAILABLE')===(r.groups.length===0));for(const g of r.groups){keys(g,['form','report_month_day','observation_count','observed_filing_windows']);need(['10-K','10-Q'].includes(g.form));day('2000-'+g.report_month_day);need(Number.isSafeInteger(g.observation_count)&&g.observation_count>0&&Array.isArray(g.observed_filing_windows));for(const w of g.observed_filing_windows){keys(w,['month','day_min','day_max','count']);need(Object.values(w).every(Number.isSafeInteger)&&w.month>=1&&w.month<=12&&w.day_min>=1&&w.day_min<=w.day_max&&w.day_max<=31&&w.count>0);}}}
  }
 }else if(name==='macro-screen.json'){
  keys(d,['axes','dimensions','cells','observations','regime','pit_status']);need(JSON.stringify(d.axes)===JSON.stringify(AXES)&&JSON.stringify(d.dimensions)===JSON.stringify(DIMENSIONS)&&d.regime===null&&['OBSERVED_BOUND_ONLY','NOT_VERIFIED'].includes(d.pit_status)&&Array.isArray(d.cells)&&d.cells.length===48&&Array.isArray(d.observations)&&d.observations.length<=10000);
  for(const [i,c]of d.cells.entries()){keys(c,['axis','dimension','state']);need(c.axis===AXES[Math.floor(i/6)]&&c.dimension===DIMENSIONS[i%6]&&['RAW_EVIDENCE','NOT_AVAILABLE'].includes(c.state)&&(c.dimension==='Level'||c.state==='NOT_AVAILABLE')&&(c.axis!=='FX'||c.state==='NOT_AVAILABLE'));}
  for(const o of d.observations){keys(o,['provider','axis','source_id','observation_period','value','unit','unit_scale','binding_sha256','available_at','source_response_sha256']);need(agencies.includes(o.provider)&&AXES.includes(o.axis)&&o.axis!=='FX'&&typeof o.source_id==='string'&&/^[A-Za-z0-9_:. -]{1,80}$/.test(o.source_id)&&typeof o.observation_period==='string'&&/^\d{4}(?:Q[1-4]|-\d{2}(?:-\d{2})?)$/.test(o.observation_period)&&typeof o.value==='string'&&/^[+-]?(?:\d+(?:\.\d*)?|\.\d+)(?:[Ee][+-]?\d+)?$/.test(o.value)&&Number.isFinite(Number(o.value))&&typeof o.unit==='string'&&(['index 1982-84=100','thousands','percent','Percent','Billions','Currency','Millions of USD'].includes(o.unit)||/^Billions of [Cc]hained /.test(o.unit))&&hash(o.binding_sha256));if(['BLS','BEA','TREASURY'].includes(o.provider))need(REGISTRY[o.source_id]?.[0]===o.provider&&REGISTRY[o.source_id]?.[1]===o.axis);else need(o.source_id===o.provider+'_SUPPLIED_BINDING'&&({FED_H41:'Liquidity',FED_H8:'Credit',TREASURY_MTS:'Fiscal'})[o.provider]===o.axis);keys(o.unit_scale,['kind','value']);const s=o.unit_scale;need(s.kind==='UNSPECIFIED'?s.value===null:s.kind==='POWER_OF_TEN'?Number.isInteger(s.value)&&Math.abs(s.value)<=30:s.kind==='MULTIPLIER'&&typeof s.value==='string'&&number(Number(s.value))&&Number(s.value)>0);const stamp=clock(o.available_at);need(stamp<=cut&&hash(o.source_response_sha256)&&sources.get(o.provider+':'+o.source_response_sha256)===stamp);states.push(fresh(stamp));}
  const present=new Set(d.observations.map(o=>o.source_id));for(const c of d.cells){const eligible=LEVEL[c.axis]?LEVEL[c.axis].every(id=>present.has(id)):d.observations.some(o=>o.axis===c.axis);need(c.state===(c.dimension==='Level'&&eligible?'RAW_EVIDENCE':'NOT_AVAILABLE'));}
  need(d.pit_status===(d.observations.length?'OBSERVED_BOUND_ONLY':'NOT_VERIFIED'));
 }else{
  keys(d,['reports','role']);need(d.role==='REPORTED_QUANTITY_CHANGE_NOT_TRADES'&&Array.isArray(d.reports)&&d.reports.length<=20);
  for(const r of d.reports){keys(r,['manager_cik','previous_quarter','current_quarter','state','changes','source_hashes']);need(typeof r.manager_cik==='string'&&/^\d{10}$/.test(r.manager_cik)&&Number(r.manager_cik)>0&&day(r.previous_quarter)<day(r.current_quarter)&&r.current_quarter<=p.as_of.slice(0,10)&&STATES.includes(r.state)&&Array.isArray(r.changes)&&(r.state!=='NOT_AVAILABLE'||!r.changes.length));states.push(r.state);refs(r,{previous:'SEC_13F',current:'SEC_13F'});
   for(const c of r.changes){keys(c,['cusip','security_key','unit','kind','reported_before','reported_after','reported_delta']);need(typeof c.cusip==='string'&&/^[0-9A-Z*@#]{9}$/.test(c.cusip)&&hash(c.security_key)&&['SH','PRN'].includes(c.unit)&&[c.reported_before,c.reported_after,c.reported_delta].every(Number.isSafeInteger)&&c.reported_before>=0&&c.reported_after>=0&&c.reported_delta===c.reported_after-c.reported_before);const a=c.reported_before,b=c.reported_after;need(c.kind===(a===0&&b>0?'NEW':b===0&&a>0?'EXIT':b>a&&a>0?'ADD':a>b&&b>0?'REDUCE':null));}
  }
 }
 need(p.state===aggregate(states));return p;
}
async function load(view){const result={};await Promise.all(Object.keys(FILES).map(async name=>{const control=new AbortController(),timer=setTimeout(()=>control.abort(),20000);try{const r=await view.fetch(name,{cache:'no-store',credentials:'omit',referrerPolicy:'no-referrer',redirect:'error',signal:control.signal});if(!r.ok)return;const chunks=[];let size=0;if(r.body?.getReader){const reader=r.body.getReader(),decoder=new TextDecoder('utf-8',{fatal:true});try{while(true){const item=await reader.read();if(item.done)break;size+=item.value.byteLength;if(size>MAX){await reader.cancel();return;}chunks.push(decoder.decode(item.value,{stream:true}));}chunks.push(decoder.decode());}finally{reader.releaseLock();}}else{const text=await r.text();need(new TextEncoder().encode(text).length<=MAX);chunks.push(text);}result[name]=validate(name,JSON.parse(chunks.join('')));}catch(_){}finally{clearTimeout(timer);}}));return result;}
// Filing-pattern windows are estimated timing (ESTIMATED_PATTERN_NOT_CONFIRMED), never a confirmed date.
function windowDates(record,year){const out=[];for(const g of record?.groups||[])for(const w of g.observed_filing_windows||[]){const start=new Date(Date.UTC(year,w.month-1,w.day_min)),end=new Date(Date.UTC(year,w.month-1,w.day_max));if(start.getUTCMonth()!==w.month-1||end.getUTCMonth()!==w.month-1)continue;out.push({form:g.form,start,end});}return out;}
function nextFilingWindow(record,now=new Date()){const today=Date.UTC(now.getUTCFullYear(),now.getUTCMonth(),now.getUTCDate());const all=[...windowDates(record,now.getUTCFullYear()),...windowDates(record,now.getUTCFullYear()+1)].filter(w=>w.end.getTime()>=today).sort((a,b)=>a.start-b.start||a.end-b.end);if(!all.length)return null;const w=all[0],md=d=>String(d.getUTCMonth()+1).padStart(2,'0')+'-'+String(d.getUTCDate()).padStart(2,'0');return{form:w.form,start:md(w.start),end:md(w.end),days_until_start:Math.max(0,Math.round((w.start.getTime()-today)/86400000)),role:'ESTIMATED_PATTERN_NOT_CONFIRMED'};}
function windowThisWeek(record,now=new Date()){const w=nextFilingWindow(record,now);return w!==null&&w.days_until_start<=6;}
// 13F: reported quantity changes only. Investor stars are device choices; the app recommends no investors.
const STAR_KEY='investment.web.v1.investor-stars';
function readStars(storage){try{const v=JSON.parse(storage.getItem(STAR_KEY)||'[]');return Array.isArray(v)?v.filter(x=>typeof x==='string'&&/^\d{10}$/.test(x)).slice(0,50):[];}catch(_){return [];}}
function toggleStar(storage,cik){need(/^\d{10}$/.test(cik));const stars=readStars(storage),next=stars.includes(cik)?stars.filter(x=>x!==cik):[...stars,cik].slice(0,50);storage.setItem(STAR_KEY,JSON.stringify(next));return next;}
function bySecurity(reports){const map=new Map();for(const r of reports)for(const c of r.changes){if(!map.has(c.cusip))map.set(c.cusip,[]);map.get(c.cusip).push({manager_cik:r.manager_cik,kind:c.kind,reported_before:c.reported_before,reported_after:c.reported_after,unit:c.unit,current_quarter:r.current_quarter});}return [...map.entries()].sort((a,b)=>a[0]<b[0]?-1:a[0]>b[0]?1:0);}
function render13F(section,p,el,en,{view='investor',storage=null,rerender=()=>{}}={}){
 section.append(el('p',en?'Source SEC EDGAR · free · filed up to 45 days after quarter end (deadline, not a freshness guarantee)':'출처 SEC EDGAR·무료 · 분기 종료 후 최대 45일 제출 기한(최신성 보장 아님)',{class:'meta'}));
 section.append(el('p',en?'Before reading: only long positions held at quarter end are reported; no shorts, bonds or cash. Reported quantity changes, not actual trades or current holdings. Not an investment signal.':'읽기 전에: 분기 말 보유분만 담기고 공매도·채권·현금은 없습니다. 보고 수량 변화이며 실제 매매·현재 보유가 아닙니다. 투자 신호 아님.',{class:'banner','data-13f-warning':''}));
 const stars=storage?readStars(storage):[],tabs=el('div',undefined,{class:'chips screen-tabs',role:'group'});for(const[id,label]of [['investor',en?'By investor':'투자자별'],['security',en?'By security':'종목별'],['overlap',en?'Overlap with mine':'내 종목과 겹침']]){const b=el('button',label,{type:'button','data-13f-view':id,'aria-pressed':String(view===id)});b.onclick=()=>rerender({view:id});tabs.append(b);}section.append(tabs);
 const reports=p.data.reports;if(!reports.length){section.append(el('p','NOT_AVAILABLE · '+(en?'No selected investor reports connected.':'연결된 투자자 보고서가 없습니다.'),{class:'empty'}));}
 if(view==='overlap'){section.append(el('p','NOT_AVAILABLE · '+(en?'CUSIP-to-company mapping is not approved. Tokyo Electron and Hanmi Semiconductor are not 13F securities.':'CUSIP→기업 대응이 승인되지 않았습니다. 도쿄일렉트론·한미반도체는 13F 대상이 아닙니다.'),{'data-13f-overlap':''}));return;}
 if(view==='security'){for(const[cusip,rows]of bySecurity(reports)){const article=el('article',undefined,{'data-13f-security':cusip});article.append(el('h3',cusip));for(const r of rows)article.append(el('p',r.manager_cik+' · '+r.kind+' · '+r.reported_before+' → '+r.reported_after+' '+r.unit));section.append(article);}return;}
 const ordered=[...reports].sort((a,b)=>Number(stars.includes(b.manager_cik))-Number(stars.includes(a.manager_cik)));
 for(const r of ordered){const article=el('article',undefined,{'data-13f-manager':r.manager_cik}),starred=stars.includes(r.manager_cik),star=el('button',starred?'★':'☆',{type:'button','data-investor-star':r.manager_cik,'aria-pressed':String(starred),'aria-label':(en?'Star investor ':'투자자 별표 ')+r.manager_cik});
  star.disabled=!storage;star.onclick=()=>{try{toggleStar(storage,r.manager_cik);}catch(_){}rerender({view});};const counts={NEW:0,ADD:0,REDUCE:0,EXIT:0};for(const c of r.changes)if(Object.hasOwn(counts,c.kind))counts[c.kind]++;
  article.append(el('h3',r.manager_cik),star,el('p',r.previous_quarter+' → '+r.current_quarter+' · '+r.state),el('p',Object.entries(counts).map(([k,v])=>k+' '+v).join(' · '),{class:'small'}));
  for(const c of r.changes)article.append(el('p',c.cusip+' · '+c.kind+' · '+c.reported_before+' → '+c.reported_after+' '+c.unit));section.append(article);}
 section.append(el('p',en?'Investor stars are stored only on this device and are included in the device backup (Settings). The app does not recommend investors.':'투자자 ★는 이 기기에만 저장되고 기기 백업(설정)에 포함됩니다. 앱이 투자자를 추천하지 않습니다.',{class:'small'}));
}
function mount(host,bundle,options={}){const {kind,companyId,companyIds,locale}=options;
 if(!host)return;const doc=host.ownerDocument,en=locale==='en-US',el=(tag,text,attrs={})=>{const n=doc.createElement(tag);if(text!==undefined)n.textContent=text;for(const[k,v]of Object.entries(attrs))n.setAttribute(k,v);return n;},section=el('section',undefined,{class:'card','data-public-screen':kind});
 const title={qg:'Q·G leaf scores / Q·G 개별 점수',types:'Company types / 가격 불필요 유형',filings:'Filing windows / 실적 예상 시기',macro:'Macro / 매크로',thirteenf:'SEC 13F'};
 section.append(el('h2',title[kind]||kind));
 const name={qg:'sec-qg-factors.json',types:'company-types-pricefree.json',filings:'sec-filing-windows.json',macro:'macro-screen.json',thirteenf:'sec-13f-changes.json'}[kind],p=bundle?.[name];
 section.append(el('p',p?.state||'NOT_AVAILABLE',{class:'badge','data-public-state':p?.state||'NOT_AVAILABLE'}));
 if(!p){section.append(el('p',en?'Public input is not connected.':'공개 입력이 연결되지 않았습니다.',{class:'empty'}));host.replaceChildren(section);return;}
 const aged=Date.now()-Date.parse(p.as_of)>p.stale_after_seconds*1000;if(aged&&p.state!=='NOT_AVAILABLE')section.append(el('p','STALE · '+(en?'Acquisition refresh overdue':'수집 갱신 시각 경과'),{class:'warning','data-public-stale':''}));
 section.append(el('p',(en?'As of: ':'기준: ')+p.as_of,{class:'meta'}));
 if(kind==='qg'||kind==='types'){section.append(el('p',en?'Provisional · Uncalibrated · No prices':'보정 전·가격 미포함',{class:'badge'}),el('p','V · NOT_AVAILABLE'));const rows=companyId?[[companyId,p.data.companies[companyId]]]:Object.entries(p.data.companies).filter(([id])=>!companyIds||companyIds.includes(id));for(const[id,r]of rows){if(!r)continue;const article=el('article',undefined,{'data-screen-company':id});article.append(el('a',id.toUpperCase(),{href:'#company/'+encodeURIComponent(id)}));const values=kind==='qg'?Object.entries(r.factors).map(([k,v])=>[k,v.score]):Object.entries(r.memberships);const list=el('dl');for(const[k,v]of values)list.append(el('dt',k),el('dd',v===null?'NOT_AVAILABLE':String(v)));article.append(list);section.append(article);}}
 else if(kind==='filings'){section.append(el('p','확정일 아님',{class:'badge'}));const rows=companyId?[[companyId,p.data.companies[companyId]]]:Object.entries(p.data.companies).filter(([id])=>!companyIds||companyIds.includes(id));for(const[id,r]of rows){if(!r)continue;const article=el('article');article.append(el('a',id.toUpperCase(),{href:'#company/'+encodeURIComponent(id)}));if(!r.groups.length)article.append(el('p','NOT_AVAILABLE'));const next=nextFilingWindow(r);if(next)article.append(el('p',(en?'Next estimated window ':'다음 예상 시기 ')+next.start+'–'+next.end+' · '+(en?'not a confirmed date':'확정일 아님'),{'data-next-window':next.start}));for(const g of r.groups)article.append(el('p',g.form+' · '+g.report_month_day+' · '+g.observed_filing_windows.map(w=>w.month+'/'+w.day_min+'–'+w.day_max+' ('+w.count+')').join(', ')));section.append(article);}}
 else if(kind==='macro'){section.append(el('p',en?'Raw evidence · Regime NOT_AVAILABLE':'원자료 참고 · 국면 NOT_AVAILABLE'));const grid=el('div',undefined,{class:'axis-grid'});for(const axis of AXES){const card=el('article',undefined,{class:'card axis-card','data-macro-axis':axis});card.append(el('h3',axis));const list=el('dl');for(const c of p.data.cells.filter(c=>c.axis===axis)){list.append(el('dt',c.dimension),el('dd',c.state,{'data-macro-state':c.dimension}));}for(const o of p.data.observations.filter(o=>o.axis===axis))card.append(el('p',o.source_id+' · '+o.observation_period+' · '+o.value+' '+o.unit));card.append(list);grid.append(card);}section.append(grid);}
 else{let storage=null;try{storage=doc.defaultView.localStorage;storage.getItem(STAR_KEY);}catch(_){storage=null;}render13F(section,p,el,en,{...options,storage,rerender:patch=>mount(host,bundle,{...options,...patch})});}
 host.replaceChildren(section);
}
return Object.freeze({FILES,STAR_KEY,validate,load,mount,nextFilingWindow,windowThisWeek,readStars,toggleStar,bySecurity});
});
