"""Build a deterministic synthetic adapter projection; no provider or runtime calls."""
from __future__ import annotations

import hashlib
import json
import sys
from pathlib import Path

HERE = Path(__file__).resolve().parent
IMPLEMENTATION = HERE.parents[2]
sys.path.insert(0, str(IMPLEMENTATION / "src"))
sys.dont_write_bytecode = True

from investment_system.product.company_price_context_v1 import period_summary, price_position


def digest(path: Path) -> str:
    return hashlib.sha256(path.read_bytes()).hexdigest()


def script_json(payload: dict) -> str:
    """Keep serialized data inert even if this JS is embedded in HTML later."""
    text = json.dumps(payload, ensure_ascii=True, indent=2, allow_nan=False)
    return text.replace("<", "\\u003c").replace(">", "\\u003e").replace("&", "\\u0026")


def validate_context(inputs: dict) -> None:
    """Reject conflicting display identity or decision stamps before projection."""
    company = inputs.get("company")
    decision = inputs.get("decision_time")
    if not isinstance(company, dict) or not isinstance(decision, str) or not decision.strip():
        raise ValueError("Missing company / decision display context")
    for field in ("security_ref", "currency"):
        if not isinstance(company.get(field), str) or not company[field].strip():
            raise ValueError("Missing company context: " + field)
    for key in ("price_position", "quarterly", "annual"):
        payload = inputs.get(key)
        if not isinstance(payload, dict) or payload.get("decision_time") != decision:
            raise ValueError("Conflicting decision context: " + key)
        records = [payload] if key != "price_position" else [payload.get(operand) for operand in ("current", "ath", "high_52w")]
        for record in records:
            if not isinstance(record, dict) or any(record.get(field) != company[field] for field in ("security_ref", "currency")):
                raise ValueError("Conflicting company context: " + key)


def build() -> dict:
    input_path = HERE / "input_sample.json"
    inputs = json.loads(input_path.read_text(encoding="utf-8"))
    if inputs.get("synthetic_only") is not True:
        raise ValueError("Only the bounded synthetic example can be rendered")
    validate_context(inputs)
    adapter = IMPLEMENTATION / "src/investment_system/product/company_price_context_v1.py"
    projection = {
        "schema": "company-analysis-phase-a-preview-v1",
        "synthetic_only": True,
        "decision_time": inputs["decision_time"],
        "company": inputs["company"],
        "price_position": price_position(inputs["price_position"]),
        "quarterly": period_summary(inputs["quarterly"]),
        "annual": period_summary(inputs["annual"]),
        "source_inputs": {key: inputs[key] for key in ("price_position", "quarterly", "annual")},
        "provenance": {
            "input_sha256": digest(input_path),
            "adapter_sha256": digest(adapter),
            "contract_sha256": digest(HERE / "input/CONTRACT.md"),
            "field_contract_sha256": digest(HERE / "input/FIELD_CONTRACT.json"),
            "source_admission": False,
            "runtime_enabled": False,
            "qgv_raw_score_input": False,
            "source_note": "Synthetic source identifiers only; no source authority is admitted.",
        },
    }
    for key in ("price_position", "quarterly", "annual"):
        if projection[key]["status"] != "AVAILABLE":
            raise ValueError(f"Synthetic fixture failed validation: {key}: {projection[key]['reason_codes']}")
    (HERE / "sample.json").write_text(json.dumps(projection, ensure_ascii=True, indent=2, allow_nan=False) + "\n", encoding="utf-8")
    (HERE / "sample.js").write_text("/* Generated by build_preview.py; do not edit. Synthetic only. */\nwindow.COMPANY_SAMPLE = " + script_json(projection) + ";\n", encoding="utf-8")
    return projection


if __name__ == "__main__":
    result = build()
    print("Built synthetic sample.json and sample.js from the validated adapter projection.")
